### ISSUE TITLE
Add supports for specifying different provider features

### ISSUE THREAD

**Issue by magodo** [Azure/aztfexport#1]
The AzureRM provider allows setting different features to change the behaviors of the resources. These behaviors might affect the way a resource is read (i.e. imported).

**Comment by LaskiBear** [comment]
For me provider parameter that im missing and because of that cant import resources is "skip_provider_registration"

**Comment by LaskiBear** [comment]
> 

Thanks that worked :)

**Comment by magodo** [comment]
This is possible via the `--provider-config`.
