### ISSUE TITLE
The `aztfy` tool doesn't properly import `azurerm_frontdoor_rules_engine` resources.

### ISSUE THREAD

**Issue by nexocentric** [Azure/aztfexport#128]
When running the `aztfy` tool the `azurerm_frontdoor_rules_engine` resources does not get imported correctly.. It shows up as a null resource instead of populated with the needed values.

```
# import example
resource "azurerm_frontdoor_rules_engine" "res-14" {
  frontdoor_name      = null
  name                = null
  resource_group_name = null
  depends_on = [
    azurerm_frontdoor.res-12,
  ]

  tags = local.tags
}
```

**Comment by magodo** [comment]
@nexocentric Thank you for submitting this, it appears the read functionality of this resource is broken in the provider.

**Comment by magodo** [comment]
A related update is that the `azurerm_frontdoor_xxx` resources are now feature frozen at the provider, and these resources are also deprecated in Azure. The replacement would be `azurerm_cdn_frontdoor_xxx` resources, which is now under development and tracked in: https://github.com/hashicorp/terraform-provider-azurerm/pull/16671
