### ISSUE TITLE
How to terrafy a storage container alone?

### ISSUE THREAD

**Issue by hguy** [Azure/aztfexport#256]
How can we do that ? There's no `resource id` for containers.
```
aztfy resource --append -k -n https://xxxxxxxxx.blob.core.windows.net/thirdtest
Error: invalid resource id: id should start with "/"
```

**Comment by magodo** [comment]
@hguy Thank you for submitting this issue!

The input of `aztfy resource` is the Azure resource id, which is not always the same as TF resource id. In this case, the cotnainer has its Azure resource manager id in form of `/subscriptions/sub1/resourceGroups/rg1/providers/Microsoft.Storage/storageAccounts/account1/blobServices/default/containers/container1`.

It's worth mentioning that, as is stated in the [README](https://github.com/Azure/aztfy#how-it-works), `aztfy` depends on `aztft` to map Azure resource id to Terraform resource type and id. In the [README](https://github.com/magodo/aztft#pesudo-resource-id) of the `aztft`, you'll find that it defines a couple of pesudo azure resource ids for data plane only or property-like resources. E.g. if you want to terrafy a data plane only resource like a container blob, then the format is like `/subscriptions/sub1/resourceGroups/rg1/providers/Microsoft.Storage/storageAccounts/account1/blobServices/default/containers/container1/blobs/blob1`.
