### ISSUE TITLE
Api error

### ISSUE THREAD

**Issue by Akky8055** [Azure/aztfexport#264]
I don't know if this is permission issue or something else, I imported rg's before didn't got this error.

Listing  Resource set:  Executing ARG query " Resources | Where ResourceGroup =~ \"rg-name\" | order by id desc" POST https://management.azure.com/providers/Microsoft.ResourceGraph/resources
‐---------‐‐----------------------------------------
RESPONSE 403: 403 Forbidden
ERROR CODE: AccessDenied
‐----------------------------------------------------
I can see I have contributor access on subscription and read access on /Microsoft.ResourceGraph/resources

Please help.

**Comment by Akky8055** [comment]
Yes I selected the correct subscription before running the aztfy. I know this is permissions issue. What permissions exactly needed for this on resource apis?

**Comment by magodo** [comment]
Per https://learn.microsoft.com/en-us/azure/governance/resource-graph/overview#permissions-in-azure-resource-graph, you at least need `read` access to the resources you want to query. Can you try above query in the Portal ARG explorer?

**Comment by Akky8055** [comment]
I did tried this in ARG, and it ran successfully.

**Comment by MohnJadden** [comment]
I'm having the exact same issue.  I have both Owner and Global Admin roles active and have used az login and Connect-AzAccount, and selected the subscription where the resource group is located. 

When I run `aztfy resource-group /subscriptions/SubscriptionGUID/resourceGroups/RGName` I get prompted to overwrite or append.  I can choose either prompt.

I then receive the following error:


```
  exporting arm template of resource group MarketingSciences-VDI: POST https://management.azure.com/subscriptions/subscriptionGUID/resourcegroups/RGName/exportTemplate      
  --------------------------------------------------------------------------------                                                                                                                              
  RESPONSE 403: 403 Forbidden                                                                                                                                                                                   
  ERROR CODE: AuthorizationFailed                                                                                                                                                                               
  --------------------------------------------------------------------------------                                                                                                                              
  {                                                                                                                                                                                                             
    "error": {                                                                                                                                                                                                  
      "code": "AuthorizationFailed",                                                                                                                                                                            
      "message": "The client 'GUIDwhichIDon'tRecognize' with object id 'GUIDwhichIDon'tRecognize' does not have authorization to perform action                                         
  'Microsoft.Resources/subscriptions/resourceGroups/read' over scope '/subscriptions/SubscriptionGUID/resourceGroups/RGName' or the scope is invalid. If access was recently 
  granted, please refresh your credentials."
    }
  }
```
  --------------------------------------------------------------------------------
It then sits and waits doing nothing until I Ctrl-C the command. 

It faults a GUID that I don't recognize - it's not the object ID for my user account that's running the command.

**Comment by magodo** [comment]
@MohnJadden `aztfy` uses the [`DefaultAzureCredential()`](https://github.com/Azure/azure-sdk-for-go/tree/main/sdk/azidentity#defaultazurecredential) internally for authentication, which will try multiple ways to auth in order. Would you please check whether you have defined certain environment variables (e.g. `ARM_CLIENT_ID`), or you are running `aztfy` in an Azure host?

**Comment by magodo** [comment]
@Akky8055 In the latest release, PR #390 brings new options `--use-environment-cred`, `--use-managed-identiy-cred` and `--use-azure-cli-cred` to allow users to explicitly choose auth method instead of the default auth chain. So in your case, you can try `--use-azure-cli-cred` to explicitly only use azure CLI auth, which should fix your issue.

I'm going to mark this issue as resolved for now, please feel free to reopen it if the issue remains.
