### ISSUE TITLE
query -r "type =~ 'microsoft.network/virtualnetworks'" skips all subnets

### ISSUE THREAD

**Issue by gioit** [Azure/aztfexport#305]
Subnets are skipped when specifying resource ID of VNET or querying for virtual networks within a resource group. Is there a way to export subnet/nsgs/route tables?

**Comment by magodo** [comment]
@gioit By running `aztfy query -r "type =~ 'microsoft.network/virtualnetworks'"` or `aztfy query -r "type =~ 'microsoft.network/virtualnetworks' and resourceGroup =~ 'your_rg_name'" `it should return you the vnets and all its child resources (including subnets). At least it works fine for me.

**Comment by gioit** [comment]
it sees the subnets with that query, but skips them on import with no way to toggle skips.

**Comment by magodo** [comment]
Would you elaborate more on this? It works fine for me:

```shell
/tmp/aztfy via 💠 default
💤  aztfy query -n -f --dev-provider -r "type =~ 'microsoft.network/virtualnetworks' and resourceGroup =~ 'acctestRG-220719133700697922'"

/tmp/aztfy via 💠 default took 26s
💤  tf state list
azurerm_subnet.res-1
azurerm_subnet_network_security_group_association.res-2
azurerm_virtual_network.res-0

```

**Comment by horen5150** [comment]
I wanted to chime in that I am also seeing this using a query similar to @magodo. It will pull in the networks and peering, but all subnets have been skipped which I can see in the aztfySkippedResources.txt file.

**Comment by magodo** [comment]
@horen5150 The reason why a resource will be skipped is that `aztft` is not able to identify its resource type automatically. Would you please share the resource id of a skipped subnet here?

**Comment by magodo** [comment]
@horen5150 Did you specify the `-r`/`--recursive` option?

**Comment by horen5150** [comment]
@magodo, yes and I do have some of the child objects, but all subnets were skipped.

**Comment by magodo** [comment]
Can you try running `aztfy` in interactive mode, then you are expected to see there is no TF resource type/name infered for the subnet resources in the import list, in this case, can you select one of the subnets and press `r` to see whether `aztfy` (actually `aztft`) can infer the resource type for it correctly?

**Comment by horen5150** [comment]
Well, while looking something up about the interactive documentation I see this:

![image](https://user-images.githubusercontent.com/22738187/219217925-9d29d90d-6a37-4e48-a8fa-e5509e0a7a57.png)

Seems like it's a known issue that relates to how aztfy processes non ARM tracked resources.

**Comment by magodo** [comment]
@horen5150 This said that a query like `type =~"microsoft.network/virtualnetworks/subnets` won't work, but `type =~ "microsoft.network/virtualnetworks"` will work. But your case is that the latter returns you the subnets, but they are not identified to be a TF resource?

**Comment by horen5150** [comment]
True, it says that it would return it with "microsoft.network/virtualnetworks", however, I didn't do it in interactive so I will give that a shot.

**Comment by horen5150** [comment]
@magodo tried in interactive and I can see the subnets, but they are also skipped with no way to save them out in the resource mapping. At this point I assume it just can't pick it up.

**Comment by magodo** [comment]
@horen5150 What is the output when you press `r` on one of those subnets in interactive mode (`r` will invoke `aztft` to provide a guess on its TF resource type)? Meanwhile, can you do me a favor to give another screenshot of that subnet's id?

**Comment by horen5150** [comment]
@magodo sorry for the delay in response, but I am working through an issue in Azure Gov with Microsoft on now the recursive function of Aztfy being broken for some reason and throwing a 403 error when it hadn't for months. I will run the interactive session again as soon as possible and try to get you that resource.

**Comment by magodo** [comment]
@horen5150 Any update?

**Comment by magodo** [comment]
:wave:

Since we've not heard back here I'm going to close this issue for the moment. Feel free to reopen if still have questions.
