### ISSUE TITLE
import terrafy isnt working, "Authenticating using the Azure CLI is only supported as a User (not a Service Principal)" error

### ISSUE THREAD

**Issue by TomHagever** [Azure/aztfexport#344]
so I was trying to import a specific resource group configuration and the resources in it using aztfy, first I used az login with my user but I got an error after I tried to import
![az login error](https://user-images.githubusercontent.com/123646788/214860743-7a88b7a2-a346-4089-bb06-abadf305a515.png)
Later on we created a service principal so that we would be able to connect instead of using a user but we ended up having a different error (attaching a screenshot and error written in topic), any idea what can I do to make this work? Is this even possible to log in with aztfy using service principal?
![service principal error](https://user-images.githubusercontent.com/123646788/214860762-84961ec9-0b28-41e9-b031-ab227e925b83.png)

**Comment by magodo** [comment]
@TomHagever I'm not sure about the first error. About the second error, yes, SP is not supported when auth using CLI. Instead, you can directly auth using SP and a secret/certificate by exporting the env vars as is stated here: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/service_principal_client_secret#configuring-the-service-principal-in-terraform

**Comment by magodo** [comment]
@TomHagever Since we haven't get further response from you, I'll mark this issue as closed for now. Feel free to reopen it if the issue still remains.
