### ISSUE TITLE
[NOTICE] This Repo Will Undergo a Name Change. Binary/Package/etc. to be Updated in the Next 1-2 weeks

### ISSUE THREAD

**Issue by stemaMSFT** [Azure/aztfexport#357]
Hi everyone,

Azure Terrafy was originally designed as a tool to help make your experience of moving infrastructure from Azure into Terraform easier. While we believe we have done our absolute best to accomplish this, we have heard from the community feedback on this name, and would like to announce that we will be changing this name in the near future. This new name will be announced in a blog post to be sent later this week, which we will update this post to link to once published. **Please expect the new name, binary, and packages to be released over the next week or two**. While this name change may unfortunately affect your current use case, please be assured that the new name will be stable moving forward, and that our commitment to designing the best experience you can have with this tool remains unchanged.

Thank you and best,
The Microsoft Terraform on Azure Team

**EDIT** The new name will be Azure Export for Terraform, and the blog post is live at https://aka.ms/AzureTerraformUpdates with other Terraform on Azure updates.

**Comment by magodo** [comment]
Just to be clear, the repo/package/cmd name will be changed from `aztfy` to `aztfexport`.

**Comment by vanmash** [comment]
Perhaps you can mention the previous name in the readme?

**Comment by magodo** [comment]
> Perhaps you can mention the previous name in the readme?

@stemaMSFT do you think we shall mention the previous name?

**Comment by stemaMSFT** [comment]
@magodo we can mention the previous name in the readme somewhere, I think that makes sense.
Closing this since the rename has been finished.
