### ISSUE TITLE
Not able to run aztfexport commands in azure devops pipeline using bash script

### ISSUE THREAD

**Issue by selvanayaki678** [Azure/aztfexport#387]
Not able to run aztfexport commands as non-interactive mode in azure devops pipeline using bash script.
Getting the below error.
![image](https://user-images.githubusercontent.com/67256407/230144042-4bbaa689-afaf-48a7-8c11-1add936d6a3d.png)
 
please anyone from team help me on this

**Comment by selvanayaki678** [comment]
Command used for above error
aztfexport rg  -n <rgname>

**Comment by magodo** [comment]
@selvanayaki678 The issue should be caused by the terminal UI module, and the ADO somehow has no tty device. Could you try running `aztfexport rg -n --plain-ui <rg-name>`?

**Comment by selvanayaki678** [comment]
Thank you.. The above command is working fine.
