### ISSUE TITLE
import resource group and include its content does not work

### ISSUE THREAD

**Issue by logcorner** [Azure/aztfexport#391]
When running  aztfexport resource-group CreatePrivateEndpointQS-rg   does not generate terraform files 

aztfexport resource-group [option] <resource group name> exports a resource group and its including resources by its name.

the arm template is attached 

I got the following error :  **Error: Unable to locate Storage Account "microcreatemyvm041719430"!**
![error](https://user-images.githubusercontent.com/5066547/232617485-2f233493-6057-4ace-95b9-629b3416eba3.png)
![output](https://user-images.githubusercontent.com/5066547/232617515-1bebe592-b571-4cae-9237-6ca2294079ee.png)
![output2](https://user-images.githubusercontent.com/5066547/232617537-1e29d6a7-d899-4096-afbe-c1433c4f5405.png)

[ExportedTemplate-CreatePrivateEndpointQS-rg.zip](https://github.com/Azure/aztfexport/files/11256009/ExportedTemplate-CreatePrivateEndpointQS-rg.zip)

**Comment by logcorner** [comment]
![error](https://user-images.githubusercontent.com/5066547/232617847-3e4e482d-776e-44f1-b131-bb04db0845eb.png)

**Comment by logcorner** [comment]
here is the exported arm template  
[ExportedTemplate-CreatePrivateEndpointQS-rg.zip](https://github.com/Azure/aztfexport/files/11256084/ExportedTemplate-CreatePrivateEndpointQS-rg.zip)

**Comment by magodo** [comment]
@logcorner There is something wrong with ARM cache for this storage account, which is a known issue in the upstream provider. You can just skip it by focusing the `azurerm_storage_account.res-16`, and enter <kbd>del</kbd>. Then press <kbd>w</kbd> to continue the process.

**Comment by magodo** [comment]
:wave:

Since we've not heard back here I'm going to close this issue for the moment. Feel free to reopen if still have questions.
