### ISSUE TITLE
[question] failures on providers/Microsoft.Sql/servers/* and one others

### ISSUE THREAD

**Issue by Pav-Bahia** [Azure/aztfexport#393]
Hi 
Could you please confirm if providers/Microsoft.Sql/servers/* and various sub elements 
and
providers/Microsoft.Network/privateEndpoints/XXXXXXXXXXXXX/privateDnsZoneGroups/default
are known problems to export..
tried another which only failed on
providers/Microsoft.Storage/storageAccounts
these are the only parts of this export that fail.. or is there a workaround.

Many Thanks in advance

**Comment by magodo** [comment]
@Pav-Bahia Yes, some resources are listable by ARM, but are actually not implemented as a separate resource in Terraform, which makes them fail during export. That is as expected, and you can simply skip them from exporting. I can confirm that at least the storage account services, and the private dns zone group under a PE belong to this category.

**Comment by magodo** [comment]
:wave:

Since we've not heard back here I'm going to close this issue for the moment. Feel free to reopen if still have questions.
