### ISSUE TITLE
403 Forbidden when running aztfexport on resource group

### ISSUE THREAD

**Issue by bhigginsah4r** [Azure/aztfexport#394]
Hi. Running into an issue where I get the following error when running aztfexport on a specific resource group. I'm owner of the subscription and can run the query in Graph Explorer

![image](https://user-images.githubusercontent.com/68560113/234367118-ea09d218-6a2c-42f1-a333-85f40fdbf354.png)

**Comment by magodo** [comment]
@bhigginsah4r If you were using Azure CLI to do auth, you probably need to ensure the default subscription is the one you expected?

**Comment by bhigginsah4r** [comment]
Yeah doing the following before each attempt. What's weird is that it works on my local workstation, I'm only getting errors when running it on azure virtual machines. 

az login
az account set --subscription "subid"

**Comment by magodo** [comment]
@bhigginsah4r Could you please provide me the log so that I can further investigate? The log can be enabled by adding options: `--log-path /tmp/log.txt --log-level=TRACE`.

**Comment by bhigginsah4r** [comment]
so when I use those switches I get Error: More than one resource groups specified. 

![image](https://user-images.githubusercontent.com/68560113/234979326-4fdb128e-1416-4c34-b8b1-96e84b0c9cbb.png)

**Comment by magodo** [comment]
The option should be placed before the resource group name.

**Comment by bhigginsah4r** [comment]
[403errorLogfile.txt](https://github.com/Azure/aztfexport/files/11354796/403errorLogfile.txt)

**Comment by bhigginsah4r** [comment]
[403errorLogfile.txt](https://github.com/Azure/aztfexport/files/11354805/403errorLogfile.txt)

Here's the log file. Looks like it's attempting to use an access token, looking at logs on successful ones from my laptop it does not use this token.

**Comment by magodo** [comment]
Thanks @bhigginsah4r! Please take a look at https://github.com/Azure/aztfexport/issues/380 for how to resolve this. Also, in the `main` branch, there is a new option `--use-azure-cli-cred` that allows you to stick on using Azure CLI to auth instead of the MSI.
