### ISSUE TITLE
Exporting application registration using aztf

### ISSUE THREAD

**Issue by serhatataman** [Azure/aztfexport#395]
How do I export an azure application registration using aztfexport? Is that supported? For reference, check my [stackoverflow question](https://stackoverflow.com/questions/76155487/how-do-i-export-existing-azure-application-registration-as-terraform-code)

**Comment by magodo** [comment]
@serhatataman The `azuread_application` belongs to the `azuread` provider, while `aztfexport` currently only support `azurerm` resources and we didn't plan to support `azuread` at this moment as it is not ARM based, but uses MS graph API.
