### ISSUE TITLE
How to auto generate Terraform script?

### ISSUE THREAD

**Issue by chaoscreater** [Azure/aztfexport#402]
I'm trying to use this in an Azure DevOps pipeline. So far, I've got something like this working without interaction from the user:

`aztfexport rg --append "1-temp-loganalyticsworkspace"`

The next step is to press "W' to import it, but this requires user interaction.

**Comment by magodo** [comment]
You can use the "--non-interactive" option: https://learn.microsoft.com/en-us/azure/developer/terraform/azure-export-for-terraform/export-terraform-concepts#non-interactive-mode

**Comment by magodo** [comment]
:wave:

Since we've not heard back here I'm going to close this issue for the moment. Feel free to reopen if still have questions.
