### ISSUE TITLE
Question: Does it support for AzureChinaCloud Enviroment ?

### ISSUE THREAD

**Issue by sanjism** [Azure/aztfexport#407]
Run below command with Azure china cloud and get the error blow. Seems the env still point to global azure tenant...

C:\ldztf>aztfexport resource-group --non-interactive --hcl-only test01
Error: listing resource set: executing ARG query "Resources | where resourceGroup =~ \"test01\" | order by id desc": DefaultAzureCredential: failed to acquire a token.
Attempted credentials:
        EnvironmentCredential: missing environment variable AZURE_TENANT_ID
        WorkloadIdentityCredential: no client ID specified. Check pod configuration or set ClientID in the options
        ManagedIdentityCredential: managed identity timed out
        AzureCLICredential: ERROR: AADSTS500011: The resource principal named https://management.core.windows.net/ was not found in the tenant named ˶��(�Ϻ�)����ó�����޹�˾. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You might have sent your authentication request to the wrong tenant.
Trace ID: 65a00e86-d240-4f65-9426-1c5fd3140200
Correlation ID: 96df22ed-716a-4621-a49c-e364b76d10ff
Timestamp: 2023-06-01 07:48:40Z
To re-authenticate, please run:
az login --scope https://management.core.windows.net//.default

**Comment by stemaMSFT** [comment]
Hey @sanjism, if you are on the latest version (0.12), you can specify the `--env` flag to change environments. Let me know if that helps!
