### ISSUE TITLE
-p does not function at all - no names or patterns are read

### ISSUE THREAD

**Issue by MohnJadden** [Azure/aztfexport#409]
I am trying to use aztfexport in order to loop through all visible resource groups and import all their resources.  I have already logged on via az cli and selected the subscription.  

When I run the command `aztfexport resource-group --use-azure-cli-cred --append -p "*"`, I get "Error: no resource group specified."  If I just search with * (no quotes), the error persists.  Same if I try a pattern  that matches existing RGs - I have several named MikeTest1, 2, 3, etc.  If I search with "Mike*" or Mike* the error persists.  

If I omit -p and just use an RG name, it returns the RG without incident, but I can't run this once per RG - it would take forever.

**Comment by stemaMSFT** [comment]
Hey @MohnJadden, I don't believe we support the syntax you're attempting to utilize here (although I could be wrong, @magodo please correct if that's the case). the `-p` flag is meant to specify naming patterns for your resources that are being exported, i.e. `azurerm_resource_group.mike-*` could be accomplished by running a `-p "mike"` in your command.
However we do enable subscription-wide resource group importing automatically through query mode. You just need to make sure you're set to the correct subscription.
`aztfexport query --use-azure-cli-cred --append --recursive "type != ''"`
This is a slightly clanky but workable fix for right now. It will find all resources within your subscription (which would thus include resource groups). 
Alternatively, if you wanted to find all resource groups from your subscription that start with "Mike" and work your way down:
`aztfexport query --use-azure-cli-cred --append --recursive "resourceGroup startswith 'Mike'"`
Would work. Let me know if that helps!
