### ISSUE TITLE
aztfexport reports permission denied - CentOS 8.5 

### ISSUE THREAD

**Issue by james-ault-nnl** [Azure/aztfexport#410]
Aztfexport is an excellent tool. Thank you for providing it.  I have used it in the past, but now it is giving me errors.
I have performed "az login" in this CentOS VM shell but I am not pasting those results here.
===

[user@centosVM aztfexport-2023-06-05.2200]$ aztfexport --version
aztfexport version v0.12.0(fc6e1ff)
[user@centosVM aztfexport-2023-06-05.2200]$ uname -a;cat /etc/centos-release
Linux centosVM 4.18.0-348.7.1.el8_5.x86_64 #1 SMP Wed Dec 22 13:25:12 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
CentOS Linux release 8.5.2111
[user@centosVM aztfexport-2023-06-05.2200]$ !1011
aztfexport rg --non-interactive rg-test-mde-jra
Error: listing resource set: executing ARG query "Resources | where resourceGroup =~ \"rg-test-mde-jra\" | order by id desc": POST https://management.azure.com/providers/Microsoft.ResourceGraph/resources
--------------------------------------------------------------------------------
RESPONSE 403: 403 Forbidden
ERROR CODE: AccessDenied
--------------------------------------------------------------------------------
{
  "error": {
    "code": "AccessDenied",
    "message": "Please provide below info when asking for support: timestamp = 2023-06-05T22:01:14.5393275Z, correlationId = b6613e4f-9e7f-4260-8646-d0fc87ff89cd.",
    "details": [
      {
        "code": "AccessDenied",
        "message": "Access is denied to the requested resource. The user might not have enough permission."
      }
    ]
  }
}
--------------------------------------------------------------------------------

[user@centosVM aztfexport-2023-06-05.2200]$ az --version
azure-cli                         2.49.0

core                              2.49.0
telemetry                          1.0.8

Extensions:
account                            0.2.2
resource-graph                     2.1.0

Dependencies:
msal                              1.20.0
azure-mgmt-resource               22.0.0

Python location '/bin/python3.9'
Extensions directory '/home/user/.azure/cliextensions'

Python (Linux) 3.9.6 (default, Aug 25 2021, 16:22:38) 
[GCC 8.5.0 20210514 (Red Hat 8.5.0-3)]

Legal docs and information: aka.ms/AzureCliLegal

Your CLI is up-to-date.

**Comment by james-ault-nnl** [comment]
same error on Ubuntu 20.04: 

user@ubu-VM:~/downloads/logs-aztfexport/aztfexp-2023-06-05.2225$ aztfexport rg --non-interactive rg-test-mde-jra
Error: listing resource set: executing ARG query "Resources | where resourceGroup =~ \"rg-test-mde-jra\" | order by id desc": POST https://management.azure.com/providers/Microsoft.ResourceGr
aph/resources
--------------------------------------------------------------------------------
RESPONSE 403: 403 Forbidden
ERROR CODE: AccessDenied
--------------------------------------------------------------------------------
{
  "error": {
    "code": "AccessDenied",
    "message": "Please provide below info when asking for support: timestamp = 2023-06-05T22:27:58.5794299Z, correlationId = 75726fa7-b2e2-47af-98e8-c5d0cd06c8b8.",
    "details": [
      {
        "code": "AccessDenied",
        "message": "Access is denied to the requested resource. The user might not have enough permission."
      }
    ]
  }
}
--------------------------------------------------------------------------------

user@ubu-VM:~/downloads/logs-aztfexport/aztfexp-2023-06-05.2225$ uname -a ;cat /etc/lsb-release 
Linux ubu-VM 5.15.0-1038-azure #45~20.04.1-Ubuntu SMP Tue Apr 25 18:45:15 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.6 LTS"
user@ubu-VM:~/downloads/logs-aztfexport/aztfexp-2023-06-05.2225$

**Comment by james-ault-nnl** [comment]
where should I look in the portal.azure.com to find permissions for azure resource graph permissions?

**Comment by magodo** [comment]
@james-ault-nnl Looks like a duplication of #380, please check out the discussion in that thread, which includes how to verify your permission, and provided a possible solution.

**Comment by magodo** [comment]
:wave:

Since we've not heard back here I'm going to close this issue for the moment. Feel free to reopen if still have questions.
