### ISSUE TITLE
Resource Graph Query To Get All Resources Within Azure V-Net

### ISSUE THREAD

**Issue by Bilal-Muhammad** [Azure/aztfexport#415]
Hi,I hope this message finds you well. I'm currently facing an issue regarding the retrieval of all resources within a specific Virtual Network (VNet) in Azure. I have attempted to use Azure Resource Graph queries to accomplish this task but haven't been successful so far.

**Comment by magodo** [comment]
I assume you are asking for an ARG query for resources (e.g. VM, storage account) belong to a specific VNet. If that is the case, it is a bit out scope of my knowledge, and also this tool..

**Comment by Bilal-Muhammad** [comment]
> I assume you are asking for an ARG query for resources (e.g. VM, storage account) belong to a specific VNet. If that is the case, it is a bit out scope of my knowledge, and also this tool..

Thanks

**Comment by magodo** [comment]
:wave:

Since we've not heard back here I'm going to close this issue for the moment. Feel free to reopen if still have questions.
