### ISSUE TITLE
Any way how to import skipped resources?

### ISSUE THREAD

**Issue by lukasNNCZ** [Azure/aztfexport#417]
Hello,
I would need your advice. I just launch aztfexport for one of our resource-group, more than 100 resources have been listed, that's ok, but many of them were (skipped). Is there any solution how to import skipped resources eventually with terrafy or it is not possible?? 
I would also like to know the reason why some resources are skipped, when trying to import them via terrafy. These resources I am talking about are for an example: 
Microsoft.Sql/servers/XYZ/advisors/CreateIndex
Microsoft.Sql/servers/XYZ/keys/ServiceManaged
I even saw a key vault or storage account in the list...

Best Regards
Lukas R.
DevOps Engineer

**Comment by magodo** [comment]
@lukasNNCZ The resource that is marked as skipped represent `aztfexport` can't find the corresponding Terraform resource type automatically. Since currently `aztfexport` should be able to map all the resource types, so it always implies those resources have no correspondance in Terraform (e.g. there is no sql server advisor/key resource in the AzureRM provider).

**Comment by lukasNNCZ** [comment]
@magodo thanks for the reply

This is the full list of skipped resources:

Following resources are marked to be skipped:

- /subscriptions/XXXXX-XXXXX-XXXXX/resourceGroups/myRGname/providers/Microsoft.RecoveryServices/vaults/defaultVaultXYZ/replicationAlertSettings/defaultAlertSetting
- /subscriptions/XXXXX-XXXXX-XXXXX/resourceGroups/myRGname/providers/Microsoft.RecoveryServices/vaults/defaultVaultXYZ/replicationVaultSettings/default
- /subscriptions/XXXXX-XXXXX-XXXXX/resourceGroups/myRGname/providers/Microsoft.Sql/servers/myServerName/advancedThreatProtectionSettings/Default
- /subscriptions/XXXXX-XXXXX-XXXXX/resourceGroups/myRGname/providers/Microsoft.Sql/servers/myServerName/advisors/CreateIndex
- /subscriptions/XXXXX-XXXXX-XXXXX/resourceGroups/myRGname/providers/Microsoft.Sql/servers/myServerName/advisors/DbParameterization
- /subscriptions/XXXXX-XXXXX-XXXXX/resourceGroups/myRGname/providers/Microsoft.Sql/servers/myServerName/advisors/DefragmentIndex
- /subscriptions/XXXXX-XXXXX-XXXXX/resourceGroups/myRGname/providers/Microsoft.Sql/servers/myServerName/advisors/DropIndex
- /subscriptions/XXXXX-XXXXX-XXXXX/resourceGroups/myRGname/providers/Microsoft.Sql/servers/myServerName/advisors/ForceLastGoodPlan
- /subscriptions/XXXXX-XXXXX-XXXXX/resourceGroups/myRGname/providers/Microsoft.Sql/servers/myServerName/auditingPolicies/Default
- /subscriptions/XXXXX-XXXXX-XXXXX/resourceGroups/myRGname/providers/Microsoft.Sql/servers/myServerName/auditingSettings/Default
- /subscriptions/XXXXX-XXXXX-XXXXX/resourceGroups/myRGname/providers/Microsoft.Sql/servers/myServerName/azureADOnlyAuthentications/Default
- /subscriptions/XXXXX-XXXXX-XXXXX/resourceGroups/myRGname/providers/Microsoft.Sql/servers/myServerName/connectionPolicies/default
- /subscriptions/XXXXX-XXXXX-XXXXX/resourceGroups/myRGname/providers/Microsoft.Sql/servers/myServerName/databases/myDBname/advancedThreatProtectionSettings/Default
- /subscriptions/XXXXX-XXXXX-XXXXX/resourceGroups/myRGname/providers/Microsoft.Sql/servers/myServerName/databases/myDBname/auditingPolicies/Default
- /subscriptions/XXXXX-XXXXX-XXXXX/resourceGroups/myRGname/providers/Microsoft.Sql/servers/myServerName/databases/myDBname/auditingSettings/Default
- /subscriptions/XXXXX-XXXXX-XXXXX/resourceGroups/myRGname/providers/Microsoft.Sql/servers/myServerName/databases/myDBname/backupLongTermRetentionPolicies/default
- /subscriptions/XXXXX-XXXXX-XXXXX/resourceGroups/myRGname/providers/Microsoft.Sql/servers/myServerName/databases/myDBname/backupShortTermRetentionPolicies/default
- /subscriptions/XXXXX-XXXXX-XXXXX/resourceGroups/myRGname/providers/Microsoft.Sql/servers/myServerName/databases/myDBname/geoBackupPolicies/Default
- /subscriptions/XXXXX-XXXXX-XXXXX/resourceGroups/myRGname/providers/Microsoft.Sql/servers/myServerName/databases/myDBname/ledgerDigestUploads/Current
- /subscriptions/XXXXX-XXXXX-XXXXX/resourceGroups/myRGname/providers/Microsoft.Sql/servers/myServerName/databases/myDBname/securityAlertPolicies/Default
- /subscriptions/XXXXX-XXXXX-XXXXX/resourceGroups/myRGname/providers/Microsoft.Sql/servers/myServerName/databases/myDBname/transparentDataEncryption/Current
- /subscriptions/XXXXX-XXXXX-XXXXX/resourceGroups/myRGname/providers/Microsoft.Sql/servers/myServerName/databases/myDBname/vulnerabilityAssessments/Default
- /subscriptions/XXXXX-XXXXX-XXXXX/resourceGroups/myRGname/providers/Microsoft.Sql/servers/myServerName/databases/master/advancedThreatProtectionSettings/Default
- /subscriptions/XXXXX-XXXXX-XXXXX/resourceGroups/myRGname/providers/Microsoft.Sql/servers/myServerName/databases/master/auditingPolicies/Default
- /subscriptions/XXXXX-XXXXX-XXXXX/resourceGroups/myRGname/providers/Microsoft.Sql/servers/myServerName/databases/master/auditingSettings/Default
- /subscriptions/XXXXX-XXXXX-XXXXX/resourceGroups/myRGname/providers/Microsoft.Sql/servers/myServerName/databases/master/geoBackupPolicies/Default
- /subscriptions/XXXXX-XXXXX-XXXXX/resourceGroups/myRGname/providers/Microsoft.Sql/servers/myServerName/databases/master/ledgerDigestUploads/Current
- /subscriptions/XXXXX-XXXXX-XXXXX/resourceGroups/myRGname/providers/Microsoft.Sql/servers/myServerName/databases/master/securityAlertPolicies/Default
- /subscriptions/XXXXX-XXXXX-XXXXX/resourceGroups/myRGname/providers/Microsoft.Sql/servers/myServerName/databases/master/transparentDataEncryption/Current
- /subscriptions/XXXXX-XXXXX-XXXXX/resourceGroups/myRGname/providers/Microsoft.Sql/servers/myServerName/databases/master/vulnerabilityAssessments/Default
- /subscriptions/XXXXX-XXXXX-XXXXX/resourceGroups/myRGname/providers/Microsoft.Sql/servers/myServerName/keys/ServiceManaged
- /subscriptions/XXXXX-XXXXX-XXXXX/resourceGroups/myRGname/providers/Microsoft.Sql/servers/myServerName/privateEndpointConnections/XYZ
- /subscriptions/XXXXX-XXXXX-XXXXX/resourceGroups/myRGname/providers/Microsoft.Sql/servers/myServerName/privateEndpointConnections/XYZ
- /subscriptions/XXXXX-XXXXX-XXXXX/resourceGroups/myRGname/providers/Microsoft.Sql/servers/myServerName/sqlVulnerabilityAssessments/Default
- /subscriptions/XXXXX-XXXXX-XXXXX/resourceGroups/myRGname/providers/Microsoft.Storage/storageAccounts/myStorageAccountName/blobServices/default
- /subscriptions/XXXXX-XXXXX-XXXXX/resourceGroups/myRGname/providers/Microsoft.Storage/storageAccounts/myStorageAccountName/fileServices/default
- /subscriptions/XXXXX-XXXXX-XXXXX/resourceGroups/myRGname/providers/Microsoft.Storage/storageAccounts/myStorageAccountName/queueServices/default
- /subscriptions/XXXXX-XXXXX-XXXXX/resourceGroups/myRGname/providers/Microsoft.Storage/storageAccounts/myStorageAccountName/tableServices/default
- /subscriptions/XXXXX-XXXXX-XXXXX/resourceGroups/myRGname/providers/Microsoft.Storage/storageAccounts/myStorageAccountName/blobServices/default
- /subscriptions/XXXXX-XXXXX-XXXXX/resourceGroups/myRGname/providers/Microsoft.Storage/storageAccounts/myStorageAccountName/fileServices/default
- /subscriptions/XXXXX-XXXXX-XXXXX/resourceGroups/myRGname/providers/Microsoft.Storage/storageAccounts/myStorageAccountName/privateEndpointConnections/myStorageAccountName.XYZ
- /subscriptions/XXXXX-XXXXX-XXXXX/resourceGroups/myRGname/providers/Microsoft.Storage/storageAccounts/myStorageAccountName/privateEndpointConnections/myStorageAccountName.XYZ
- /subscriptions/XXXXX-XXXXX-XXXXX/resourceGroups/myRGname/providers/Microsoft.Storage/storageAccounts/myStorageAccountName/queueServices/default
- /subscriptions/XXXXX-XXXXX-XXXXX/resourceGroups/myRGname/providers/Microsoft.Storage/storageAccounts/myStorageAccountName/tableServices/default
- /subscriptions/XXXXX-XXXXX-XXXXX/resourceGroups/myRGname/providers/Microsoft.Storage/storageAccounts/myStorageAccountName/blobServices/default
- /subscriptions/XXXXX-XXXXX-XXXXX/resourceGroups/myRGname/providers/Microsoft.Storage/storageAccounts/myStorageAccountName/fileServices/default
- /subscriptions/XXXXX-XXXXX-XXXXX/resourceGroups/myRGname/providers/Microsoft.Storage/storageAccounts/myStorageAccountName/queueServices/default
- /subscriptions/XXXXX-XXXXX-XXXXX/resourceGroups/myRGname/providers/Microsoft.Storage/storageAccounts/myStorageAccountName/tableServices/default

For some of them I found correspondent resource in terraform, for example Microsoft.Sql servers/connectionPolicies which is marked as skipped as well.
https://learn.microsoft.com/en-us/azure/templates/microsoft.sql/servers/connectionpolicies?pivots=deployment-language-terraform
or Microsoft.Storage storageAccounts/blobServices here: https://learn.microsoft.com/en-us/azure/templates/microsoft.storage/storageaccounts/fileservices/shares?pivots=deployment-language-terraform

Maybe I am missing something here, but it's strange to me, because as per these links above, is it possible to have these resources in terraform.

**Comment by magodo** [comment]
@lukasNNCZ Both of the highlighted resource types are modeled in their parent resource in Terraform:

- For Microsoft.Sql/servers/connectionPolicies, I believe it corresponds to the [`connection_policy`](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/sql_server#connection_policy) property in `azurerm_sql_server` resource
- For Microsoft.Storage/storageAccounts/blobServices, it is modeled in `azurerm_storage_account`

**Comment by lukasNNCZ** [comment]
> @lukasNNCZ Both of the highlighted resource types are modeled in their parent resource in Terraform:
> 
> * For Microsoft.Sql/servers/connectionPolicies, I believe it corresponds to the [`connection_policy`](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/sql_server#connection_policy) property in `azurerm_sql_server` resource
> * For Microsoft.Storage/storageAccounts/blobServices, it is modeled in `azurerm_storage_account`

yeah I saw that in the documentation, so that's the reason why they cannot be imported by terrafy?

**Comment by stemaMSFT** [comment]
@lukasNNCZ I will let @magodo correct me if I'm wrong, but yes. Terraform AzureRM will at times define resources within properties (another example is subnet, which can be defined within the property of a vnet or as its own independent resource). These two aren't exposed directly as individual resources, which is why they can't be mapped.

**Comment by magodo** [comment]
@lukasNNCZ Instead of "not importing" them, they are already imported as properties in some other resource.

Since this is how `aztfexport` is designed to be, I'm gonna close this issue for now. If you have any other questions, feel free to reopen it.
