### ISSUE TITLE
 Error: open /dev/tty: no such device or address available

### ISSUE THREAD

**Issue by sphtd** [Azure/aztfexport#422]
Hi, I want to make a workflow in github actions to perform imports, but unfortunately I have an error with the command:

aztfexport resource-group -n -k --output-dir "$output_dir" "resourcegroup"

Error: open /dev/tty: no such device or address available
Error: process terminated with exit code 1.

**Comment by magodo** [comment]
@sphtd The `/dev/tty` is used by both interactive and non-interactive mode to output info. Would you please try adding an additional option `--plain-ui` to make those info are output to stderr only?

**Comment by sphtd** [comment]
@magodo Thanks for help, It works! I think you should add this option to --help or maybe i didn't found this :)?

**Comment by magodo** [comment]
No, I didn't. I'll add it and then close this issue.
