### ISSUE TITLE
One file with provider and backend

### ISSUE THREAD

**Issue by sphtd** [Azure/aztfexport#424]
Hi, I have another question. is it possible to configure it so that the backend and the provider are added to the main.tf file, and not in separate files?

`terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "3.50.0"
    }
    github = {
      source  = "integrations/github"
      version = "5.28.0"
    }
  }

  backend "azurerm" {
    subscription_id      = ""
    resource_group_name  = ""
    storage_account_name = ""
    container_name       = ""
    key                  = ""
  }
}`

**Comment by magodo** [comment]
Unfortunately, there isn't such an option yet. As Terraform treats files in one folder as a whole, and Terraform prefer to have the resources and provider/terraform config in separate files, we are not gonna to combine them into one in the near future. If you'd like to combine them, you can do that by yourself (e.g. using `cat`).
