### ISSUE TITLE
Unable to import resources using aztfexport

### ISSUE THREAD

**Issue by Akp212** [Azure/aztfexport#426]
Hello Team,

I was trying to import resources using aztfexport resource-group but facing error below:
![image](https://github.com/Azure/aztfexport/assets/29576232/371bad1d-0b40-44e6-9e35-fbcb38f5393e)

I am trying to run az login first and after az login I am running above commands. If there is any clue how i can fix this please let me know.
note: this is public cloud account.

**Comment by magodo** [comment]
@Akp212 You can specify `--use-azure-cli-cred` to explicitly use Azure CLI to do auth.

**Comment by magodo** [comment]
The option should be before the positional argument (as mentioned in the USAGE): `aztfexport resource-group --use-azure-cli-cred Translator_jira`

**Comment by Akp212** [comment]
It's working now. Thanks for the help
