### ISSUE TITLE
Running behind a proxy

### ISSUE THREAD

**Issue by fprobst** [Azure/aztfexport#432]
We're trying the **aztfexport** tool but there is no connection to _terraform.io_ through our http proxy:
```
Could not retrieve the list of available versions for provider
  hashicorp/azurerm: could not query provider registry for
  registry.terraform.io/hashicorp/azurerm: the request failed after 2 attempts,
  please try again later: Get
  "https://registry.terraform.io/v1/providers/hashicorp/azurerm/versions":
  net/http: request canceled while waiting for connection (Client.Timeout
  exceeded while awaiting headers)

        * task error: error running terraform init: exit status 1
```
The environment variables **http_proxy/https_proxy** are set and when I'm trying a curl on the URL it succeedes:
```
PS U:\> curl https://registry.terraform.io/v1/providers/hashicorp/azurerm/versions                                      

StatusCode        : 200
StatusDescription : OK
Content           : {"id":"hashicorp/azurerm","versions":[{"version":"2.31.1","protocols":["5.0"],"platforms":[{"os":"l
                    inux","arch":"386"},{"os":"freebsd","arch":"arm"},{"os":"linux","arch":"amd64"},{"os":"linux","arch
                    ":...
RawContent        : HTTP/1.1 200 OK
                    Transfer-Encoding: chunked
                    Connection: keep-alive
                    Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
                    Vary: Accept-Encoding
                    X-Cache: RefreshHit from cloudfront...
Forms             : {}
Headers           : {[Transfer-Encoding, chunked], [Connection, keep-alive], [Strict-Transport-Security,
                    max-age=31536000; includeSubDomains; preload], [Vary, Accept-Encoding]...}
Images            : {}
InputFields       : {}
Links             : {}
ParsedHtml        : mshtml.HTMLDocumentClass
RawContentLength  : 100498
```
Is there a possibility to set a proxy for the application, may be in the configuration?

Thanks!

Kind regards,
Florian

**Comment by magodo** [comment]
@fprobst I'm using `https_proxy` env var. The tool itself doesn't do too much of API call, `terraform` itself honors `https_proxy` as well. So you can probably test whether your setting works with plain `terraform init`.

**Comment by fprobst** [comment]
Thanks for the quick reply! I tried a **terraform init** and it works without problems:
```
> terraform init

Initializing the backend...

Initializing provider plugins...
- Reusing previous version of hashicorp/azurerm from the dependency lock file
- Using previously-installed hashicorp/azurerm v3.65.0

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
```
Should I try to do a re-init the terraform modules/providers?
The https_proxy env is set on my windows machine.

**Comment by magodo** [comment]
No need to re-init. Is your above error occurs systematically? Sometimes there might be errors accessing the Terraform registry, as is reported by: https://github.com/Azure/aztfexport/issues/379. This is mostly due to network issue, but not the bug of this tool.

**Comment by fprobst** [comment]
Thanks for sharing the link. I tried the hints in the issue:
```
terraform version
	=> 1.2.9 updated to latest version 1.5.3
	
aztfexport version
	=> 0.13.0
	
curl https://registry.terraform.io/.well-known/terraform.json
	=> HTTP 200
	
aztfexport query “‘resourceGroup =~ 'your_rg_name'"
	=> also failing with latest terraform
```
Terraform is working fine, but aztfexport is still raising the error that it can not query available provider packages.
Any ideas what else can be the issue or what I can test?

**Comment by magodo** [comment]
@fprobst It is working fine for me:

```shell
$ export https_proxy=https://localhost:8080
$ aztfexport rg -n -f aztfy-vmdisk
```

The `mitmproxy` sniffers the traffic as expected:

![image](https://github.com/Azure/aztfexport/assets/7970698/698dc7ad-a83d-4662-9f43-7509178051eb)

That said, the `aztfexport` doesn't do anything special, it just invokes `terraform` as a child process to do the init.

**Comment by fprobst** [comment]
@magodo I tried your options but there is still the same error. A collegue with a Mac will now execute the export for me :)
I think we can close this issue. Unfortunately it will not work on my Windows PC 😞
