### ISSUE TITLE
Azure custom role definition import issue

### ISSUE THREAD

**Issue by asifkd012020** [Azure/aztfexport#435]
Hello Team,

I am trying to import Azure custom role definitions and the aztfexport errors out saying the invalid role definition id format.

 Microsoft Azure Export for Terraform 

  /providers/Microsoft.Authorization/roleDefinitions/2e83062e-c364-05bb-8567-a100ba7215d1

  exit status 1

  Error: could not parse Role Definition ID, invalid format
  "/providers/Microsoft.Authorization/roleDefinitions/2w41628n-d468-41sb-8567-a100ba7215d1"

**Comment by magodo** [comment]
Thank you for reporting this! The error derives from the AzureRM provider https://github.com/hashicorp/terraform-provider-azurerm/blob/b2c2cdad6cab5866d58e07852c40719d83c91e00/internal/services/authorization/parse/role_definition.go#L17-L29:

```go
// RoleDefinitionId is a pseudo ID for storing Scope parameter as this it not retrievable from API
// It is formed of the Azure Resource ID for the Role and the Scope it is created against
func RoleDefinitionId(input string) (*RoleDefinitionID, error) {
	parts := strings.Split(input, "|")
	if len(parts) != 2 {
		return nil, fmt.Errorf("could not parse Role Definition ID, invalid format %q", input)
	}

	idParts := strings.Split(parts[0], "roleDefinitions/")

	if !strings.HasPrefix(parts[1], "/subscriptions/") && !strings.HasPrefix(parts[1], "/providers/Microsoft.Management/managementGroups/") {
		return nil, fmt.Errorf("failed to parse scope from Role Definition ID %q", input)
	}
```

As the comment has said, `aztft` has no way to get the scope from API, only the users who created this role has that knowledge. So there is really not too much we can do here, but instruct users to modify the resource mapping file to construct the correct resource id, or use `aztfexport res` to export them one by one afterwards.
