### ISSUE TITLE
403 Forbidden Error when running the AZTFExport tool

### ISSUE THREAD

**Issue by nhsram** [Azure/aztfexport#442]
We are running this tool from a VM in our corporate network and we are running this tool against a resource group. 

The account that is running this command with a PowerShell command let has got the permissions (Contributor) for the target resource group and for the subscription which the target resource group contains. 

We are using the following command
`
aztfexport rg --non-interactive -parallelism 5 --log-level "TRACE" -f myRgName
`
This resulted with the following error.

--------------------------------------------------------------------------------
RESPONSE 403: 403 Forbidden
ERROR CODE: AccessDenied
--------------------------------------------------------------------------------
{
  "error": {
    "code": "AccessDenied",
    "message": "Please provide below info when asking for support: timestamp = 2023-08-10T10:14:12.4422036Z, correlationId = 101025ab-08ce-454d-a17f-6273d86d3bef.",
    "details": [
      {
        "code": "AccessDenied",
        "message": "Access is denied to the requested resource. The user might not have enough permission."
      }
    ]
  }
}
--------------------------------------------------------------------------------
We are able to run below query and can view the results.

aztfexport query --non-interactive --parallelism 5 -f "resourceGroup =~'myRgName'"

Just to add that the principalID that is getting the permission denied have Contributor role on the Management group and if the command is executed using Search-AzGraph -Query the principal can list the resources.

Could someone help us to fix this error please?

**Comment by nhsram** [comment]
Just to add that the principalID that is getting the permission denied have Contributor role on the Management group and if the command is executed using Search-AzGraph -Query the principal can list the resources.

**Comment by magodo** [comment]
@nhsram Thank you for submitting this issue! This really looks weired to me, as the `rg` subcommand under the hood is also using the ARG to query the resources, plus it will put the resource group itself to the returned resource list: https://github.com/Azure/aztfexport/blob/6b91f93f0adb8a50414f372fda38696e4cf912f3/internal/meta/meta_rg.go#L84-L113

Persumably, you intended to use azure CLI auth method, whilst the default auth method chain ends up using the MSI as you are on an Azure VM. If that is the case, you can use `--use-azure-cli-cred` explicitly, see: https://github.com/Azure/aztfexport/issues/401.

**Comment by magodo** [comment]
:wave:

Since we've not heard back here I'm going to close this issue for the moment. Feel free to reopen if still have questions.
