### ISSUE TITLE
Support for ARM_STORAGE_USE_AZUREAD

### ISSUE THREAD

**Issue by TwinTechLLC** [Azure/aztfexport#445]
I'm trying to run an export against storage accounts that enforce azure ad authentication.  This is supported in terraform itself through the ARM_USE_AZUREAD or ARM_STORAGE_USE_AZUREAD options.  Is there way to have this supported in aztfexport? Right now, I error on storage accounts due to key based auth being disabled.

**Comment by magodo** [comment]
Related to #1

**Comment by TwinTechLLC** [comment]
There was a trick in #1 that helped.  

Originally I was doing this:

```
  ARM_USE_AZUREAD=true
  ARM_STORAGE_USE_AZUREAD=true
  aztfexport resource-group -n --plain-ui --append example-rg
```

It worked when I added `export`:

```
  export ARM_USE_AZUREAD=true
  export ARM_STORAGE_USE_AZUREAD=true
  aztfexport resource-group -n --plain-ui --append terraform-state
```

**Comment by TwinTechLLC** [comment]
> For the provider configurations that have environment variable support (e.g. the `ARM_STORAGE_USE_AZUREAD`), you can directly set it and run the `aztfexport`:
> 
> ```
> ARM_STORAGE_USE_AZUREAD=true aztfexport rg <your rg>
> ```
> 
> It would then be picked up by the provider properly.

Thank you for the quick reply, it's much appreciated.
