### ISSUE TITLE
failed to import in China Azure

### ISSUE THREAD

**Issue by Shanon666** [Azure/aztfexport#450]
I have changed the environment to "china", while when I enter “w” to import, it shows error which indicates it connect to Global （Public）Azure other than China Azure . 

I have set the environment to China Azure both in Azure CLI and computer environment variables.

I also tried connect to China Azure with  parameter --scope  (az login --scope https://microsoftgraph.chinacloudapi.cn/.default) to redirect it to China Azure ，while the issue still here. 

![image](https://github.com/Azure/aztfexport/assets/58842626/49580b0a-f89b-4024-805f-e4677951fc8a)

![image](https://github.com/Azure/aztfexport/assets/58842626/6a598248-7243-4fee-8390-be27f4f6a9d5)

**Comment by magodo** [comment]
This has already been supported.
