### ISSUE TITLE
Loop Through Resource Groups

### ISSUE THREAD

**Issue by melovagabond** [Azure/aztfexport#451]
Hello,
I was trying to create a script to loop through resource groups and run the command against each one sequentially:

```
import os
import subprocess

# List of resource group names
RESOURCE_GROUPS = [
    "group1",
    "group2",
    "group3",
    "group4",
    "group5",
    "group6",
    "group7"
]

# Loop through each resource group
for group in RESOURCE_GROUPS:
    # Check if the folder already exists
    if not os.path.exists(group):
        # Create a folder matching the resource group name
        os.makedirs(group)

    # Run the aztfexport command in the newly created folder
    os.chdir(group)
    subprocess.run(['aztfexport', 'resource-group', group, '--non-interactive'])
    os.chdir('..')
```
However I just get this Error Message:
Error: More than one resource groups specified

Is there a way to get this to process incrementally?

**Comment by magodo** [comment]
The `group` is a positional argument, which should be the last argument in your `.run` slice.

**Comment by melovagabond** [comment]
Thank you! That works! If anyone is curious, to use this script:

```python
import os
import subprocess

# Read resource group names from a file
with open('resource_groups.txt') as file:
    RESOURCE_GROUPS = [line.strip() for line in file]

# Loop through each resource group
for group in RESOURCE_GROUPS:
    # Check if the folder already exists
    if not os.path.exists(group):
        # Create a folder matching the resource group name
        os.makedirs(group)

    # Run the aztfexport command in the newly created folder
    os.chdir(group)
    subprocess.run(['aztfexport', 'resource-group', '--non-interactive', group])
    os.chdir('..')
```

Login to your Azure account
```bash
az login
```
List your subscriptions
```bash
az account list --output-table
```
Set the Subscription
```bash
az az account set --subscription ${subscriptionID} # replacing ${subscriptionID} with corresponding ID related to folder
```
Grap a list of resource groups and save it as a file

```bash
az group list --query "[].name" --output tsv > resource_groups.txt
```

Run the script 
```bash
python3 importLoop.py
```

This will loop through each group, create a folder with the same name as the group, and run the aztfexport command in that folder.

**Comment by vikashbond** [comment]
I am trying use this tool to export my environment resources using command:
**devOps***@MasterJenkins:~/DevOps-***/terraform/terraform-******-new$ aztfexport resource-group rg-ywc-dev --output /home/devOps***/DevOps-***/terraform/terraform-****-new**

every time getting this error "**Error: More than one resource groups specified**" even though I am using correct Resource group name, there is no syntax error, no extra space no commas.

Why this is happening and how can I resolve this?

**Comment by magodo** [comment]
@vikashbond Simply move your options ahead of the resource group name.

**Comment by vikashbond** [comment]
Thank you for response this helped a lot.
