### ISSUE TITLE
when importing, all resources was shown as import failed

### ISSUE THREAD

**Issue by rizkyfaza20** [Azure/aztfexport#453]
Hi i got the issues while exporting manually, I got accessed to the resources group and try to export the resource group by myself, and try with the command with :

`aztfexport rg --use-azure-cli-cred my-resource-group`

and now I get the throwback for each resources, and one of them shown like this : 
`/subscriptions/00000-0000000-00000000-000000/resourceGroups/my-resource-group/providers/Microsoft.Logic/workflows/logic-hhtp-dev-weu-001-dagcodes-year/actions/Initialize__vVolgnr import failed`

what step that I missed while exporting, is there any missing config that I do?

**Comment by magodo** [comment]
You can press <kbd>e</kbd> on any of them to view the error details.

**Comment by edchumpitaz** [comment]
@rizkyfaza20 Did you ever get this figured out? I'm seeing his in some of my export attempts as well.

**Comment by magodo** [comment]
Normally, those resources are built-in resources that are managed fully by their parent resources, and are not expected to be exported.

**Comment by rizkyfaza20** [comment]
@edchumpitaz i managed to skip the resource to make sure i can deploy, i guess that was for the resolution for now
