### ISSUE TITLE
Resource Name Creating with "_"

### ISSUE THREAD

**Issue by soumikcal** [Azure/aztfexport#454]
When I am generating tf for RG it is generating Resource Name with "_" and terraform plan/apply is failing as "_" not accept in Resource Name. Please find snippet and error as follows.

resource "azurerm_container_registry_scope_map" "res-5" {
  actions                 = ["repositories/*/content/read"]
  container_registry_name = "pathfindercr"
  description             = "Can pull any repository of the registry"
  **name                    = "_repositories_pull"**
  resource_group_name     = "ava-pathfinder"
  depends_on = [
    azurerm_container_registry.res-3,
  ]
}

Error:

 **Error: alpha numeric characters and hyphens only are allowed in "name": "_repositories_pull"
│
│   with azurerm_container_registry_scope_map.res-5,
│   on main.tf line 44, in resource "azurerm_container_registry_scope_map" "res-5":
│   44:   name                    = "_repositories_pull"**

**Comment by magodo** [comment]
The validation is from the provider, and this `_repositories_pull` resource sounds like a built-in resource managed by the ACR? So you probably can skip this resource.

**Comment by soumikcal** [comment]
Understand
