### ISSUE TITLE
Resource Import Issues, Including APIM - Need Clarification

### ISSUE THREAD

**Issue by gogo25171** [Azure/aztfexport#470]
Hello everyone,

I recently attempted to import Azure resources, particularly APIM, using Azure Terrafy, but I encountered some difficulties. I'm wondering if there are any known limitations or issues that could explain why this import is not working as expected.

I'd like to request community assistance to clarify a few points. Here are some assumptions I have in mind, but I'm open to other insights:

- Running Resource Issues: Could there be import problems when the Azure resource, like APIM, is in a running state or has states that make import challenging?

- Complexity and Dependencies: Can complex resources with many dependencies pose import issues? Are there any guidelines for managing such situations?

- Resource Support: Does Azure Terrafy currently not support certain Azure resources, including APIM? If so, is there a timeline for updates to add these features?

- Other Issues: Are there any other factors or problems that I may not have considered?

I appreciate any assistance, information, or examples of successful use cases. This will not only help me but also other community members who may encounter similar issues.

Thank you in advance for your help!

Best regards

**Comment by magodo** [comment]
Hi @gogo25171, I'm answering your questions as following:

- Running Resource Issues: There is no issue for resources in running state
- Complexity and Dependencies: The terraform cross resource dependencies will be added as long as you have specified these resources to be exported together. E.g. if your APIM and its dependencies are in the same resource group, and you specify the resource group to be exported  (i.e. via the `resource-group` mode), then all of them are exported with cross dependencies correctly added
- Resource Support: Currently, all resources supported by AzureRM can be exported in theory (e.g. when you use the `resource` mode). Whilst some resources won't be listed when using the `resource-group` or `query` mode, especially for those data plane resources.
- Other Issues: Please check on https://learn.microsoft.com/en-us/azure/developer/terraform/azure-export-for-terraform/export-terraform-concepts#limitations for more limitations

**Comment by magodo** [comment]
:wave:

Since we've not heard back here I'm going to close this issue for the moment. Feel free to reopen if still have questions.
