### ISSUE TITLE
Win 10 error export example

### ISSUE THREAD

**Issue by FPignalosa75** [Azure/aztfexport#471]
Hello to all,
I followed the below steps in my environment Win 10

Install Terraform and Environment Cfg
 
https://learn.microsoft.com/en-us/azure/developer/terraform/get-started-windows-bash?tabs=bash
 
Azure to Terraform Export
 
https://learn.microsoft.com/en-us/azure/developer/terraform/azure-export-for-terraform/export-first-resources?tabs=azure-cli
 
After try to export my resorse group obtain the below error

Error: initializing provider for the import directories: 10 errors occurred:
        * task error: error running terraform init: exit status 1

Error: Failed to query available provider packages

Could not retrieve the list of available versions for provider
hashicorp/azurerm: could not connect to registry.terraform.io: failed to
request discovery document: Get
"https://registry.terraform.io/.well-known/terraform.json": net/http: request
canceled while waiting for connection (Client.Timeout exceeded while awaiting
headers)

Could you please give me support?

**Comment by magodo** [comment]
This indicates something wrong with your network to connect to the terraform registry site. Assuming the same issue exist when you run `terraform init`.

**Comment by FPignalosa75** [comment]
I read this message after execute terraform init command
PS C:\temp\terraform> terraform init

Initializing the backend...

Initializing provider plugins...
- Reusing previous version of hashicorp/azurerm from the dependency lock file
- Using previously-installed hashicorp/azurerm v3.65.0

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.

**Comment by magodo** [comment]
The log states that you are reusing a pre-installed provider, which indicates that there is no network access actually occured. Would you mind to specify another provider version which is not available in your local and try `terraform init` again to test the network?

**Comment by magodo** [comment]
You can create an empty folder somewhere, create a `main.tf` file in this folder with below content:

```hcl
terraform {
  required_providers {
    azurerm = {
      source = "hashicorp/azurerm"
      version = "3.79.0"
    }
  }
}

provider "azurerm" {
  features {}
}
```

Then run `terraform init` in there.

**Comment by FPignalosa75** [comment]
@magodo thanks for your support.
Below the result
PS C:\terraform_3_79_0> terraform init

Initializing the backend...

Initializing provider plugins...
- Finding hashicorp/azurerm versions matching "3.79.0"...
- Installing hashicorp/azurerm v3.79.0...
- Installed hashicorp/azurerm v3.79.0 (signed by HashiCorp)

Terraform has created a lock file .terraform.lock.hcl to record the provider
selections it made above. Include this file in your version control repository
so that Terraform can guarantee to make the same selections by default when
you run "terraform init" in the future.

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.

What's are the next steps? @magodo

**Comment by magodo** [comment]
@FPignalosa75 Then you can try the same step, but replacing `terraform init` with `aztfexport <...>`. Especially, you can try `aztfexport rg -provider-version=3.79.0 <rgname>`

**Comment by FPignalosa75** [comment]
@magodo thanks for the support. I executed various tests
PS C:\git\Aztfy-demo> aztfexport rg -provider-version=3.79.0 ExampleResourceGroup
Error: More than one resource groups specified
PS C:\git\Aztfy-demo> aztfexport rg ExampleResourceGroup -provider-version=3.79.0
Error: More than one resource groups specified
PS C:\git\Aztfy-demo> aztfexport resource-group ExampleResourceGroup -provider-version=3.79.0
Error: More than one resource groups specified

The response is the same in all case. What am I doing wrong?

**Comment by magodo** [comment]
It should be `--provider-version` instead of `-provider-version`, sorry for the typo in my last msg.

**Comment by FPignalosa75** [comment]
Hello @magodo,
I found that the problem depends on the network policy of the company where I work.
Thanks a lot for the support.
