### ISSUE TITLE
Response 400 : There must be at least one subscription that is eligible to contain resources.

### ISSUE THREAD

**Issue by TheGrumpyTechnician** [Azure/aztfexport#475]
Hello everyone,

I am quite new to IaC and have been tasked to get some Azure resources into Terraform since they were made in the GUI. I have owner privileges and am able to create resources throughout the entire tenant. 

During my testing from https://learn.microsoft.com/en-us/azure/developer/terraform/azure-export-for-terraform/export-first-resources?tabs=azure-cli

I keep getting the following issue 

  listing resource set: executing ARG query "Resources | where resourceGroup =~ \"TestResourceGroup\" | order by id desc": POST   
  https://management.azure.com/providers/Microsoft.ResourceGraph/resources                                                        
  --------------------------------------------------------------------------------                                                
  RESPONSE 400: 400 Bad Request                                                                                                   
  ERROR CODE: BadRequest                                                                                                          
  --------------------------------------------------------------------------------                                                
  {                                                                                                                               
    "error": {                                                                                                                    
      "code": "BadRequest",                                                                                                       
      "message": "Please provide below info when asking for support: timestamp = 2023-11-15T16:52:50.2223078Z, correlationId =    
  c98e9f8c-90d5-45a0-99ac-b6bda4e99d3c.",                                                                                         
      "details": [                                                                                                                
        {                                                                                                                         
          "code": "NoValidSubscriptionsInQueryRequest",                                                                           
          "message": "There must be at least one subscription that is eligible to contain resources. Given:                       
  'e215bcd9-ce0a-4c88-bdf1-5e5b286455df'."                                                                                        
        }                                                                                                                         
      ]                                                                                                                           
    }                                                                                                                             
  }                                                                                                                               
  --------------------------------------------------------------------------------     
  
How do I fix this? We have 2 subscriptions within our tenant but I deleted the one that is no longer used since it was from a previous vendor we were using.

**Comment by TheGrumpyTechnician** [comment]
so I got it to work...but now I have another issue 



  │ ❗️/subscriptions/4fbb8e21-c4df-499f-919f-1e8af9d64f3e/resourceGroups/TestResourceGroup
  │ azurerm_resource_group.res-0

    ❗️/subscriptions/4fbb8e21-c4df-499f-919f-1e8af9d64f3e/resourceGroups/TestResourceGroup/providers/Microsoft.Compute/virtualMachines/ 
    azurerm_linux_virtual_machine.res-1

    ✅/subscriptions/4fbb8e21-c4df-499f-919f-1e8af9d64f3e/resourceGroups/TestResourceGroup/providers/Microsoft.Network/networkInterfaces  resource.
    azurerm_network_interface.res-2

    ❗️/subscriptions/4fbb8e21-c4df-499f-919f-1e8af9d64f3e/resourceGroups/TestResourceGroup/providers/Microsoft.Network/networkInterface 
    azurerm_network_interface_security_group_association.res-3

    ❗️/subscriptions/4fbb8e21-c4df-499f-919f-1e8af9d64f3e/resourceGroups/TestResourceGroup/providers/Microsoft.Network/networkSecurityG 
    azurerm_network_security_group.res-4

    ✅/subscriptions/4fbb8e21-c4df-499f-919f-1e8af9d64f3e/resourceGroups/TestResourceGroup/providers/Microsoft.Network/networkSecurityGr 
    azurerm_network_security_rule.res-5

    ❗️/subscriptions/4fbb8e21-c4df-499f-919f-1e8af9d64f3e/resourceGroups/TestResourceGroup/providers/Microsoft.Network/publicIPAddresse 
    azurerm_public_ip.res-6

    ❗️/subscriptions/4fbb8e21-c4df-499f-919f-1e8af9d64f3e/resourceGroups/TestResourceGroup/providers/Microsoft.Network/virtualNetworks/ 
    azurerm_virtual_network.res-7

    ❗️/subscriptions/4fbb8e21-c4df-499f-919f-1e8af9d64f3e/resourceGroups/TestResourceGroup/providers/Microsoft.Network/virtualNetworks/ 
    azurerm_subnet.res-8

**Comment by magodo** [comment]
@TheGrumpyTechnician You can select the errored ones and press <kbd>e</kbd> to show the error message.

**Comment by TheGrumpyTechnician** [comment]
@magodo  Ah thank you. my monitor wasn't showing the options on the bottom. root of the cause was `az clear ` and then 

```
az account list -o table
az account set -s 
```

it started working after that.

**Comment by ritikaguptams** [comment]
@TheGrumpyTechnician if you dont mind sharing how did you fix the NoValidSubscriptionsInQueryRequest. I keep getting Given '.'
