### ISSUE TITLE
Issue With Installation in Azure Function SSH 

### ISSUE THREAD

**Issue by Kamalhello** [Azure/aztfexport#481]
I want to install this Package in Azure function SSH which has configuration as follows. 
Distributor ID: Debian
Description:    Debian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye
I couldn't be able to install it the Azure function SSH.
Kindly provide me the Steps for Installion  in Azure function SSH or Should I have to use alternate Azure Services to use this Package.

**Comment by magodo** [comment]
Unfortunately, we are not supporting bullseye at the moment. Alternatively, you can download it directly from the github release: e.g. https://github.com/Azure/aztfexport/releases/tag/v0.14.0

**Comment by magodo** [comment]
:wave:

Since we've not heard back here I'm going to close this issue for the moment. Feel free to reopen if still have questions.
