### ISSUE TITLE
Encountered an error while exporting resources with aztfexport: "cmd.exe" is not found in the %PATH%.

### ISSUE THREAD

**Issue by Zaxorinox** [Azure/aztfexport#484]
What confuses me is that the "cmd.exe" (system32) is whitening the PATH. I am running this from a Windows 11 machine with those ### versions.

az CLI :
  {
  "azure-cli": "2.54.0",
  "azure-cli-core": "2.54.0",
  "azure-cli-telemetry": "1.1.0",
  "extensions": {
    "account": "0.2.5"
  }
}
Terraform : 
Terraform v1.4.5

aztfexport : 
aztfexport version v0.13.1(c690456)

=========================

After Running: aztfexport resource-group --use-azure-cli-cred RG_TEST

Got this : 

  listing resource set: executing ARG query "Resources | where resourceGroup =~ \"RG_TEST\" | order by id desc": AzureCLICredential: exec:    
  "cmd.exe": executable file not found in %PATH%

**Comment by magodo** [comment]
@Zaxorinox This duplicates to https://github.com/Azure/aztfexport/issues/119, see my comment: https://github.com/Azure/aztfexport/issues/119#issuecomment-1139323764
