### ISSUE TITLE
aztfexport query error 

### ISSUE THREAD

**Issue by balagcpcloud** [Azure/aztfexport#485]
Hello Team, 

When I try to export the terraform scripts for Microsoft.Network types, I am facing with the errors ,
Could you please help? 

Command :  aztfexport query -g -r -n "resourceGroup =~ DEV-T24' and type contains 'Microsoft.Network'"

****************************************************************
--------------------------------------------------------------------------------
RESPONSE 400: 400 Bad Request
ERROR CODE: BadRequest
--------------------------------------------------------------------------------
{
  "error": {
    "code": "BadRequest",
    "message": "Please provide below info when asking for support: timestamp = 2023-12-04T16:43:28.2015623Z, correlationId = c2c2c2f0-56f3-4ea3-b485-c0aabb23889c.",
    "details": [
      {
        "code": "InvalidQuery",
        "message": "Query is invalid. Please refer to the documentation for the Azure Resource Graph service and fix the error before retrying."
      },
        "code": "ParserFailure",
        "message": "ParserFailure",
        "expectedToken": "'"
      },
      {
        "code": "ParserFailure",
        "message": "ParserFailure",
        "line": 1,
        "characterPositionInLine": 42,
        "token": "' and type contains '"
      }
    ]
  }
}
--------------------------------------------------------------------------------

**Comment by magodo** [comment]
There is a missing opening quote in `DEV-T24'`?

**Comment by magodo** [comment]
:wave:

Since we've not heard back here I'm going to close this issue for the moment. Feel free to reopen if still have questions.
