### ISSUE TITLE
Getting error while importing Network interface

### ISSUE THREAD

**Issue by ChaturvediSwati** [Azure/aztfexport#487]
Getting error parsing network interface Ip configurations unexpected segment "ipConfigurations/ipconfig1" present at the end of the URI

**Comment by magodo** [comment]
@ChaturvediSwati Would you elaborate more about the failure, including the resource id being exported, and the exact error message that is raised?

**Comment by ChaturvediSwati** [comment]
@magodo it would not be possible to share, apologies for the inconvenience. But I have observed that network interface with IP configurations as static allocation method, giving above error, however if tried with dynamic IPs of network interface, it is working as expected.

Could you please let me know any way to import network interface with IP allocation method as static?

**Comment by magodo** [comment]
Could you try to manually import this resource by `terraform import`?

**Comment by ChaturvediSwati** [comment]
I tried importing using terraform import, I was able to import the tfstate file with network interface configurations as static allocation method.

**Comment by magodo** [comment]
Then I guess it is because the tool is exporting this resource as a different TF resource type. I can hardly help if there is no more detail provided..

**Comment by magodo** [comment]
:wave:

Since we've not heard back here I'm going to close this issue for the moment. Feel free to reopen if still have questions.

**Comment by mbaniadam** [comment]
Hi, same issue here! 

PS E:\AzureExport> aztfexport query -n -k -o rg-example-test-01 --parallelism 25 --plain-ui --overwrite --provider-version 3.98 --backend-type=azurerm --backend-config=resource_group_name=rg-mgmt-01 --backend-config=storage_account_name=satfstates --backend-config=container_name=rg-example-test-01 --backend-config=key=rg-example-test-01 "resourceGroup =~ 'rg-example-test-01'"

>>
Error: parsing "/subscriptions/xxxxxxxxxxxxxxxxxxxxxxxxxx/resourceGroups/rg-example-test-01/providers/Microsoft.Network/networkInterfaces/w-scoring-t01-ip/ipConfigurations/ipconfig1": unexpected segment "ipConfigurations/ipconfig1" present at the end of the URI (input "/subscriptions/xxxxxxxxxxxxxxxxxxxxxxxxxx/resourceGroups/rg-example-test-01/providers/Microsoft.Network/networkInterfaces/w-scoring-t01-ip/ipConfigurations/ipconfig1")

------------------------------------------------------------------------------------
**Terraform Block created by aztfexport:**

}
resource "azurerm_network_interface" "res-47" {
  location            = "westeurope"
  name                = "nzexpe98563b4387-ccc2-47be-8e52-31d5342ae10a"
  resource_group_name = "rg-example-test-01"
  ip_configuration {
    name                          = "ipConfignzexpe98563b4387-ccc2-47be-8e52-31d5342ae10a"
    private_ip_address_allocation = "Dynamic"
    subnet_id                     = "/subscriptions/xxxxxxxxxxxxxxxxxxxxxxxxxx/resourceGroups/example-connections-01/providers/Microsoft.Network/virtualNetworks/vnet-example-connections-01/subnets/snet-test-01"
  }
}

------------------------------------------------------------------------------------


**Same result with manual import using Terraform Import.**

PS E:\AzureExport\rg-example-test-01> terraform import azurerm_network_interface.res-47 "/subscriptions/xxxxxxxxxxxxxxxxxxxxxxxxxx/resourceGroups/rg-example-test-01/providers/Microsoft.Network/networkInterfaces/w-example-t01-ip/ipConfigurations/ipconfig1
>> "
azurerm_network_interface.res-47: Importing from ID "/subscriptions/xxxxxxxxxxxxxxxxxxxxxxxxxx/resourceGroups/rg-example-test-01/providers/Microsoft.Network/networkInterfaces/w-example-t01-ip/ipConfigurations/ipconfig1\n"...
╷
│ Error: parsing "/subscriptions/xxxxxxxxxxxxxxxxxxxxxxxxxx/resourceGroups/rg-example-test-01/providers/Microsoft.Network/networkInterfaces/w-scoring-t01-ip/ipConfigurations/ipconfig1\n": unexpected segment "ipConfigurations/ipconfig1\n" present at the end of the URI (input "/subscriptions/xxxxxxxxxxxxxxxxxxxxxxxxxx/resourceGroups/rg-example-test-01/providers/Microsoft.Network/networkInterfaces/w-example-t01-ip/ipConfigurations/ipconfig1\n")
