### ISSUE TITLE
AzureGov export not producing main.tf file

### ISSUE THREAD

**Issue by edchumpitaz** [Azure/aztfexport#488]
I'm new to working with aztfexport. After a few attempts, I was able to get the correct flags to begin the export. Once it completes, I see the aztfexportResourceMapping.json, import.tf, provider.tf, and terraform.tf files but not the main.tf file. I tried with and without the --hcl-only flag with no luck. Any insight would be appreciated. Are there additional steps I must take to get the main.tf file? The goal is to get the main.tf file and use it to deploy/redeploy this exported RG & Resources in a test/dev sub.

Command I'm using is aztfexport rg --hcl-only --env "usgovernment" rgname

**Comment by magodo** [comment]
@edchumpitaz Could you please share the log so that I can further look into, as the command seems correct to me. Also it worth mentioning that "reproduce" the provisioning is a [non-goal](https://github.com/Azure/aztfexport?tab=readme-ov-file#non-goal) of this tool.

**Comment by stonehj** [comment]
I'm having the same issue, did you manage to get it working?

**Comment by magodo** [comment]
Fixed by #546.
