### ISSUE TITLE
China Azure

### ISSUE THREAD

**Issue by m1rl0k** [Azure/aztfexport#490]
I get errors when trying to authenticate to use tfexport against az china;

![image](https://github.com/Azure/aztfexport/assets/11264689/8512cd05-ab6d-4ba0-9136-eaba66932015) this is without a service principal;

this is with service principal and azureprofile.json set to to use; ![image](https://github.com/Azure/aztfexport/assets/11264689/74fa5c2a-87af-47b2-8e9c-7759a0edb557)

obviously have set to azure china cloud, did az login.. gave owner to service principal on the sub trying to read... have tried multiple resource groups; etc what may i be missing? Any insights @magodo

**Comment by magodo** [comment]
@m1rl0k I've tested via the SP auth way (i.e. `ARM_CLIENT_ID` + `ARM_CLIENT_SECRET`), would you mind give that a try? Currently, I don't have an Azure China account to test the CLI auth scenario.

**Comment by magodo** [comment]
Update: I've successfully to make `aztfexport` work for China cloud via CLI auth, by the following steps:

1. `az cloud set --name AzureChinaCloud`
2. `az login --service-principal <options>`
3. `aztfexport <command> <options>`
