### ISSUE TITLE
aztfexport is missing in AUR

### ISSUE THREAD

**Issue by olfolfolf** [Azure/aztfexport#496]
As per readme, aztfexport should be available in archlinux user repository (AUR), but It's missing.

```
yay -S aztfexport
 -> No AUR package found for aztfexport
 there is nothing to do
```

I could find aztfy-bin in AUR, but it's outdated.

**Comment by magodo** [comment]
Hey @olfolfolf

Thank you for this reminder! Since AUR is not one of the official supported platform, I personally maintain this. Apparently I've been lazy for a while.. The package is now updated to the latest version v0.14.0: https://aur.archlinux.org/packages/aztfy-bin.

**Comment by olfolfolf** [comment]
Hey @magodo, 
thanks for your response. Unfortunately it's not working, the url is wrong:

```
==> Retrieving sources...
  -> Downloading aztfy_v0.14.0_linux_amd64.zip...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     9    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404
==> ERROR: Failure while downloading https://github.com/Azure/aztfy/releases/download/v0.14.0/aztfy_v0.14.0_linux_amd64.zip
    Aborting...
 -> error downloading sources: /home/ap04/.cache/yay/aztfy-bin
         context: exit status 1
```

**Comment by magodo** [comment]
@olfolfolf Indeed.. I've fixed the URLs and verified it works. Ensure to redownload the PKGBUILD via: `yay -S --redownload aztfy-bin`.

**Comment by magodo** [comment]
@olfolfolf I have no access to my archlinux machine these days and in the next following days. Please directly use the binary from the github release as a work around. I'll update the AUR once I have the chance, sorry.
