### ISSUE TITLE
AZTFY Installation issues

### ISSUE THREAD

**Issue by ICantCodeEtAl** [Azure/aztfexport#506]
Running Windows 11. Have Terraform installed in "C:\Terraform", have an environmental variable set up pointing to C:\Terraform. Ran the MSI downloaded from github for Terrafy. Copied the exe to "C:\Terraform", set $env for Path "C:\Program Files\aztfexport". Closed VS Code and opened as admin. Getting the following: 
"aztfy: The term 'aztfy' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again."

What am I doing wrong?

**Comment by magodo** [comment]
@ICantCodeEtAl The name of the executable is now called `aztfexport` (instead of `aztfy`). Also if you put it under `C:\Program Files`, then the path shall just be `C:\Program Files`, not its full path `C:\Program Files\aztfexport`.

**Comment by ICantCodeEtAl** [comment]
I am an absolute moron. I was staring the exe in the face and kept saying "Why aren't you working with AZFTY !" No issues at all, thank you. New to Terraform and Azure, and like my name says... Appreciate the response, ready to learn some more.
