### ISSUE TITLE
[BUG] Error while installing hashicorp/azurerm v3.77.0: local error: tls: bad record MAC

### ISSUE THREAD

**Issue by Racle** [Azure/aztfexport#507]
New to this tool. 

After running "Initializing" for little while, it throws error: (4 times same error)

```
initializing provider for the import directories: 4 errors occurred:
        * task error: error running terraform init: exit status 1

  Error: Failed to install provider

  Error while installing hashicorp/azurerm v3.77.0: local error: tls: bad record MAC
```

I'm trying to export resource group with `aztfexport resource-group my-rg-group-name`.
I'm already logged in with `az login`.
It creates `provider.tf  .terraform  .terraform.lock.hcl  terraform.tf` files to current folder.

If I run these commands terraform seems to be working just fine
```
> rm .terraform* -rf
> terraform init

Initializing the backend...

Successfully configured the backend "local"! Terraform will automatically
use this backend unless the backend configuration changes.

Initializing provider plugins...
- Finding hashicorp/azurerm versions matching "3.77.0"...
- Installing hashicorp/azurerm v3.77.0...
- Installed hashicorp/azurerm v3.77.0 (signed by HashiCorp)

Terraform has created a lock file .terraform.lock.hcl to record the provider
selections it made above. Include this file in your version control repository
so that Terraform can guarantee to make the same selections by default when
you run "terraform init" in the future.

Terraform has been successfully initialized!
```

Is there some step I'm missing with this tool, or is this just broken for now?

```
Pop!_OS 22.04 LTS

Terraform v1.7.4

"azure-cli": "2.58.0",
"azure-cli-core": "2.58.0",
"azure-cli-telemetry": "1.1.0"

aztfexport version dev // installed with go get
```

**Comment by Racle** [comment]
Quick update.

Relogged with `az login` (even while everything seemed to work)
Ran `aztfexport resource-group --provider-name=azapi my-rg-group-name`
Now it seems to be importing data with azapi. seems like that default provider failed for some reason.

**Comment by magodo** [comment]
@Racle `bad record MAC` is a very internal error, which usually means network corruption of some sorts (like a proxy changing the contents of the TCP stream), or a severe issue in the TLS stack.\

So would you please double check your network setup, or try to target to a different provider version of `azurerm` via `--provider-version`?

**Comment by Racle** [comment]
@magodo tried using  version 3.95.0, 3.0.0 and 2.99.0, all have same problem.

And like I said earlier, after removing terraform hidden files and running `terraform init`, it works as intented and it downloads provider correctly without any errors (but doesn't export resource group of course), so I'm wondering why that can download and install provider correctly while this tool seems to fail the same thing.

**Comment by magodo** [comment]
@Racle That is weired... As the tool actually is doing nothing special up to the init part:

- Construct the `terraform.tf` and `provider.tf` it not available
- Running `terraform init` via https://github.com/hashicorp/terraform-exec

One thing you can do is to use the `--dev-provider` option, which will skip the `terraform init`, but it requires you have manually initialize the provider, or [setup the dev provider settings](https://developer.hashicorp.com/terraform/cli/config/config-file#development-overrides-for-provider-developers) beforehead.

**Comment by magodo** [comment]
:wave:

Since we've not heard back here I'm going to close this issue for the moment. Feel free to reopen if still have questions.

**Comment by nitin12384** [comment]
Probably one of those issues that just get fixed on retry.  Didn't change a thing, and it fixed on its own.
```
➜  ~/Workspace/kuknitin/shared/Misc/terraform/learn-terraform-init git:(main) ✗ [4:33:07] terraform init
Initializing the backend...
Initializing modules...
- ec2-instance in modules/aws-ec2-instance
Downloading registry.terraform.io/joatmon08/hello/random 4.0.0 for hello...
- hello in .terraform/modules/hello
Initializing provider plugins...
- Finding hashicorp/aws versions matching "5.43.0"...
- Finding hashicorp/random versions matching "3.6.0"...
- Installing hashicorp/aws v5.43.0...
- Installing hashicorp/random v3.6.0...
- Installed hashicorp/random v3.6.0 (signed by HashiCorp)
╷
│ Error: Failed to install provider
│
│ Error while installing hashicorp/aws v5.43.0: local error: tls: bad record MAC
╵
➜  ~/Workspace/kuknitin/shared/Misc/terraform/learn-terraform-init git:(main) ✗ [4:33:20] terraform init
Initializing the backend...
Initializing modules...
Initializing provider plugins...
- Finding hashicorp/aws versions matching "5.43.0"...
- Finding hashicorp/random versions matching "3.6.0"...
- Installing hashicorp/aws v5.43.0...
- Installed hashicorp/aws v5.43.0 (signed by HashiCorp)
- Installing hashicorp/random v3.6.0...
- Installed hashicorp/random v3.6.0 (signed by HashiCorp)
Terraform has created a lock file .terraform.lock.hcl to record the provider
selections it made above. Include this file in your version control repository
so that Terraform can guarantee to make the same selections by default when
you run "terraform init" in the future.

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
➜  ~/Workspace/kuknitin/shared/Misc/terraform/learn-terraform-init git:(main) ✗ [4:37:52]
```
