### ISSUE TITLE
rg argument does not display the resource group or any resources within the group

### ISSUE THREAD

**Issue by MohnJadden** [Azure/aztfexport#513]
When I run aztfexport with the --resource-group argument, aztfexport runs for a moment and then shows no resource groups or resources found.  I confirmed that my user account and my machine identity both have the Reader role on the resource group and all resources within the group.  I've retried az login several times and the issue persists.  

This is with v0.14.0.

**Comment by stemaMSFT** [comment]
@MohnJadden can you confirm the full command you're running here? Feel free to redact any sensitive info.

**Comment by MohnJadden** [comment]
@stemaMSFT 
I'm running `./aztfexport rg  --output-dir "newdir"  resourcegroupname`

Output looks like:

`
   Microsoft Azure Export for Terraform 

     resourcegroupname 

    No items

  No items found.
`

**Comment by stemaMSFT** [comment]
Does the output change when using the `--use-azure-cli-cred` command?

**Comment by tsjake** [comment]
I am having the same issue.  In my case it sees the resource group, but no resources under it.

**Comment by magodo** [comment]
:wave:

Since we've not heard back here I'm going to close this issue for the moment. Feel free to reopen if still have questions.

**Comment by elit0451** [comment]
I experienced the same issue when running the `aztfexport resource-group -o newDir resourcegroupname` command. And it seems like using the correct casing for the `resourcegroupname` solved the problem 😁 

I used `az group list` to fetch all resource groups and verify their names.

**Comment by magodo** [comment]
@elit0451 That's weird since Azure is case insensitive on input, while only terraform is case sensitive. Assuming there are a list of resources in the skip file?

**Comment by akzov** [comment]
> 👋
> 
> Since we've not heard back here I'm going to close this issue for the moment. Feel free to reopen if still have questions.

@magodo who are you waiting to hear back from? This is still broken a year later.

**Comment by magodo** [comment]
In the `main` branch, we added a new option `--include-managed-resource` to allow the previously skipped managed resources (incl. resource group) to be exported.

**Comment by akzov** [comment]
So if I create a vnet or a storage account using the Azure Web UI that's a managed resource? Because it worked when I last did it in Jan.
