### ISSUE TITLE
can we use resourcechanges query with aztfexport? 

### ISSUE THREAD

**Issue by harshitjain5june** [Azure/aztfexport#514]
I was looking for a way for importing resources that are created in last 7days using aztfexport, I worked with aztfexport , to import resources whose type is not `Microsoft.Insights` and it worked fine using queries.

But when I try to use resourcechanges query, it gives an error or no item found, because by default it uses resources query only.

i was trying to integrate this type of query with aztfexport:
`resourcechanges 
|extend targetResourceId = tostring(properties.targetResourceId), changeType = tostring(properties.changeType), createTime = todatetime(properties.changeAttributes.timestamp) 
| where createTime > ago(7d) and changeType == "Create" or changeType == "Update" or changeType == "Delete"
| project  targetResourceId, changeType, createTime 
| join ( resources | extend targetResourceId=id) on targetResourceId
| where tags ['Environment'] =~ 'prod' 
| order by createTime desc 
| project createTime, id, resourceGroup, type`

is there a way I can use this query with aztfexport?

**Comment by magodo** [comment]
This query is a comlicated enough for the CLI.. Instead, you can run the query and retrieve a list of resource ids, then we can consider extend the tool to accept a list of resources in the `resource` mode to support your use case.
