### ISSUE TITLE
Importing Resource Groups Still Doesn't work

### ISSUE THREAD

**Issue by tsjake** [Azure/aztfexport#520]
when I run aztfexport rg <rg id> it tells me all the resources are skipped, additionally it only shows one resource despite there being 14 in the group.  I tried the --use-azure-cli-cred flag and it tells me there's multiple resource groups defined.  

This is with 0.14.1

**Comment by stemaMSFT** [comment]
Hey @tsjake what's the full command you're running?

**Comment by tsjake** [comment]
> Hey @tsjake what's the full command you're running?

I ran:
aztfexport rg <id> and also --use-azure-cli-cred

**Comment by stemaMSFT** [comment]
if your command is `aztfexport rg --use-azure-cli-cred myResourceGroup` then this does just seem like a bug.
Does running `aztfexport query --use-azure-cli-cred --recursive "type =~ 'microsoft.compute/virtualmachines' and name == 'myResourceGroup'"` solve the problem? Replace `myResourceGroup` with your RG of course.

**Comment by magodo** [comment]
@tsjake Can you please share the generated mapping file `aztfexportResourceMapping.json`?

**Comment by magodo** [comment]
Closing for no response from author.
