### ISSUE TITLE
Error: Failed to import providers/Microsoft.Storage/storageAccounts/

### ISSUE THREAD

**Issue by diepes** [Azure/aztfexport#525]
aztfexport -v
aztfexport version v0.14.1(f492475)

Running:
```
aztfexport query \
    --output-dir="$out_dir" \
    --subscription-id="$AZTFEXPORT_SUBSCRIPTION_ID" \
    --provider-name="azurerm" \
    --provider-version="3.99.0" \
    -n "resourceGroup =~ '$AZTFEXPORT_RG'"
```

it starts fine
`⣾  Initializing ...`
`⣾  Listing resources`
`⣾  Importing resources ...`

Completes Importing for 35/36 and then fails with 
Error:
```
Error: Failed to import /subscriptions/23...96/resourceGroups/dev-bp-rg/providers/Microsoft.Storage/storageAccounts/bpshare as azurerm_storage_account.res-35: exit status 1

Error: retrieving queue properties for Storage Account (Subscription: "23...96"
Resource Group Name: "dev-bp-rg"
Storage Account Name: "bpshare"): unmarshalling response: could not parse response body
```

**Comment by magodo** [comment]
@diepes Could you please try manually import this resource via `terraform import`? If the issue remains, then please submit an issue in the upstream repo: https://github.com/hashicorp/terraform-provider-azurerm/issues/new/choose

**Comment by magodo** [comment]
:wave:

Since we've not heard back here I'm going to close this issue for the moment. Feel free to reopen if still have questions.
