### ISSUE TITLE
Import.tf file after v0.14.2

### ISSUE THREAD

**Issue by brojtar** [Azure/aztfexport#539]
Hello there,

In prior versions (0.14.0) the aztfexport creates a import.cf file wich contains all the import from ids to terraform. The last version doesnt create this file. is there a way to mantain this file creation?

With the aztfexportResourceMApping.json i cannot import to my tfstate the resources, and i need to create from 0 the import.tf.

Thanks!

**Comment by hterik** [comment]
See https://github.com/Azure/aztfexport/pull/516
