### ISSUE TITLE
Cannot export te resource group using hcl-only and non-interactive flag

### ISSUE THREAD

**Issue by rajesh-ms** [Azure/aztfexport#544]
Just used the simple command: aztfexport rg --non-interactive --hcl-only <rg-xyz>

Recevied following error: rror: Failed to import /subscriptions/<sub-id>/resourceGroups/<rg-name>/providers/Microsoft.ApiManagement/service/<apim-xyz>/subscriptions/master as azurerm_api_management_subscription.res-65: exit status 1

Error: parsing scope into product/ api id "/subscriptions/<sub-id>/resourceGroups/<rg-name>/providers/Microsoft.ApiManagement/service/<apim-xyz>/": parsing "/subscriptions/<sub-id>/resourceGroups/<rg-name>/providers/Microsoft.ApiManagement/service/<apim-xyz>/": parsing the Api ID: the number of segments didn't match

Expected a Api ID that matched (containing 10 segments):

> /subscriptions/<sub-id>/resourceGroups/example-resource-group/providers/Microsoft.ApiManagement/service/serviceValue/apis/apiIdValue

However this value was provided (which was parsed into 0 segments):

> /subscriptions/<sub-id>/resourceGroups/<rg-name>/providers/Microsoft.ApiManagement/service/<apim-xyz>/

The following Segments are expected:

* Segment 0 - this should be the literal value "subscriptions"
* Segment 1 - this should be the UUID of the Azure Subscription
* Segment 2 - this should be the literal value "resourceGroups"
* Segment 3 - this should be the name of the Resource Group
* Segment 4 - this should be the literal value "providers"
* Segment 5 - this should be the name of the Resource Provider [for example 'Microsoft.ApiManagement']
* Segment 6 - this should be the literal value "service"
* Segment 7 - this should be the user specified value for this service [for example "serviceValue"]
* Segment 8 - this should be the literal value "apis"
* Segment 9 - this should be the user specified value for this apiId [for example "apiIdValue"]

The following Segments were parsed:

* Segment 0 - not found
* Segment 1 - not found
* Segment 2 - not found
* Segment 3 - not found
* Segment 4 - not found
* Segment 5 - not found
* Segment 6 - not found
* Segment 7 - not found
* Segment 8 - not found
* Segment 9 - not found

Any suggestion, anything missing ?

**Comment by magodo** [comment]
Hi @rajesh-ms, this duplicates to https://github.com/Azure/aztfexport/issues/444, please subscribe that for any update!
