### ISSUE TITLE
error finding a terraform exectuable

### ISSUE THREAD

**Issue by jmeidam** [Azure/aztfexport#549]
I just tried to use `aztfexport`, but get an error with the first attempt. It claims it cannot find my terraform executable in `PATH`, even though my shell is able to find it.

The exact error is as follows:

```
  error finding a terraform exectuable: unable to find, install, or build from 1 sources: 1 error occurred:
        * terraform: executable file not found in $PATH
```

The command I was trying to use:

```aztfexport resource --output-dir ./testtf /subscriptions/***/resourceGroups/***/providers/Microsoft.Logic/workflows/***```

Version of `aztfexport` is v0.14.2(523f5b8). Version of `terraform` is v1.6.5-dev (higher than the required v0.12).
I am running from Linux within WSL. The command `which terraform` shows a path that is also listed in `PATH`.

Log level "DEBUG" gives no additional information

**Comment by magodo** [comment]
This duplicates to #547. See my comment for the reason: https://github.com/Azure/aztfexport/issues/547#issuecomment-2268072688

**Comment by jmeidam** [comment]
apologies for posting a duplicate. I must have used the wrong prompts when searching for an existing answer
