### ISSUE TITLE
Azure Policy Support for Definitions and Assignments

### ISSUE THREAD

**Issue by Pbolkun** [Azure/aztfexport#550]
It would be great if we could export Azure Policy Definition and Policy Assignments. When you use the `az definition show` and `az assignment show` commands with appropriate queries you can export the definitions, but to get those into HCL can be tedious. It especially becomes a problem when you attempt to export an entire initiative definition set. 

Look forward to seeing if there's any support here!

**Comment by magodo** [comment]
There is an option: `--include-role-assignment` that allows you to export role assignments directly assigned to the resources being exported.

**Comment by Pbolkun** [comment]
That's fantastic to hear that role assignments are supported! When I mention Azure Policy assignments, I'm referring to a global resource that helps to enforce organizational standards and to assess compliance at-scale. Through its compliance dashboard, it provides an aggregated view to evaluate the overall state of the environment. https://learn.microsoft.com/en-us/azure/governance/policy/overview

**Comment by magodo** [comment]
@Pbolkun I'm sorry to mix the role vs policy..

The policy assignment/definition can be exported by the `aztfexport res` command, by providing the resource id.

You can get the list of those ids via `az`, e.g. for assignments:

```
az policy assignment list | jq -r '.[].id'
```

In order to export a bunch of assignments and definitions, you can construct a rseource map file, then fed it to `aztfexport map` command.

Idealy, it helps if the `aztfexport res` subcommand can take a list of resource ids,  so that you can just list all the resource ids of the assignments and definitions. Is that something you are seeking for?

**Comment by jefutte** [comment]
@magodo while a list of resources like #552 helped me, it would also be great to have aztfexport query understand ARG queries fully. Tried using `policyresources | where type == 'microsoft.authorization/policydefinitions' | where properties.policyType == 'Custom'` but it fails with the below error:
`--------------------------------------------------------------------------------
RESPONSE 400: 400 Bad Request
ERROR CODE: BadRequest
--------------------------------------------------------------------------------
{
  "error": {
    "code": "BadRequest",
    "message": "Please provide below info when asking for support: timestamp = 2024-09-25T12:10:37.6190263Z, correlationId = 582a865b-380f-4e46-80e3-5414a725ea65.",
    "details": [
      {
        "code": "InvalidQuery",
        "message": "Query is invalid. Please refer to the documentation for the Azure Resource Graph service and fix the error before retrying."
      },
      {
        "code": "Operator_FailedToResolveEntity",
        "message": "'where' operator: Failed to resolve scalar expression named 'policyresources'"
      },
      {
        "code": "Default",
        "message": "Filter expression should be Boolean"
      }
    ]
  }
}
--------------------------------------------------------------------------------`
<img width="1188" alt="image" src="https://github.com/user-attachments/assets/bb2bb410-ab96-431a-a039-b2f08d8ac863">

**Comment by stemaMSFT** [comment]
@magodo what's the complexity of supporting copy-paste of preexisting ARG queries? I know that in this scenario we could just use the `and` operator repeatedly, but thought it's worth asking.

**Comment by magodo** [comment]
@stemaMSFT The reason to restrict the KQL is to avoid too flexible usage that might change the returned data format, which can breaks the assumption of the program.

While I revisited the ARG [tables](https://learn.microsoft.com/en-us/azure/governance/resource-graph/concepts/query-language#resource-graph-tables), looks like the (default) `Resources` doesn't contain all the available resource types. So probably we should allow users to specify the table name.
