### ISSUE TITLE
General suggestion : Terraform Provider is re-downloaded on every execution, even if it already exists

### ISSUE THREAD

**Issue by arun6106** [Azure/aztfexport#555]
The AzureRM provider is downloaded on every execution of aztfexport, even when it already exists in the .terraform folder.
`\.terraform\providers\registry.terraform.io\hashicorp`

This causes long wait times on the initialization step, as the provider is > 230 MB

This can probably be moved to a central location like %localappdata% and reused then on, for subsequent executions of aztfexport

**Comment by magodo** [comment]
@arun6106 You can setup the Terraform provider cache to avoid repeated downloading.
