### ISSUE TITLE
Export fails and comes back to resources list, when there are Skipped entries present

### ISSUE THREAD

**Issue by arun6106** [Azure/aztfexport#556]
First of all, great aztfexport is a initiative and works brilliantly well!

We have run across an issue though which we'd like to mention, as there's probably a solution already -

While doing an export using **w** button and the **listed resources contains** some **(skip)** entries (usually happens for storage accounts, network policies), 
The export does start properly, goes till 100% but instantly comes back to the **list resources** screen and does not export anything (no main.tf or resource export happens, no error in UI either)

Command used
`aztfexport.exe  resource-group -o <output folder name> <ResourceGroupName>`

![SkipError](https://github.com/user-attachments/assets/7e331a80-c825-46ac-b1e0-f66ccf483e26)

upon adding `--non-interactive --continue` to the arguments, it does go on and export the HCL configuration, 
but still throws an error on the console at the end, and all the resources marked with Skip, are not exported. 

Is there a workaround available or fix planned for this ?

Error attached below:

```⢿  Importing resources...
Errors:
Failed to import /subscriptions/<subscriptionId>/resourceGroups/rg-network/providers/Microsoft.Network/serviceEndpointPolicies/_e41f87a2_mi_1cf06d4843b6-82f6-471f54f37a96 as azurerm_subnet_service_endpoint_storage_policy.res-164: exit status 1
 
Error: retrieving Subnet Service Endpoint Storage Policy "_e41f87a2_mi_1cf06d4843b6-82f6-471f54f37a96" (Resource Group "rg-network"): network.ServiceEndpointPoliciesClient#Get: Failure responding to request: StatusCode=200 - Original Error: Error occurred unmarshalling JSON - Error = 'json: cannot unmarshal object into Go struct field ServiceEndpointPolicyPropertiesFormat.contextualServiceEndpointPolicies of type string' JSON = '{
  "name": "_e41f87a2_mi_1cf06d4843b6-82f6-471f54f37a96",
  "id": "/subscriptions/<subscriptionId>/resourceGroups/rg-network/providers/Microsoft.Network/serviceEndpointPolicies/_e41f87a2_mi_1cf06d4843b6-82f6-471f54f37a96",
  "etag": "W/\"2c6e16a0-73c4-a7ce-d731dc4f161b\"",
  "type": "Microsoft.Network/serviceEndpointPolicies",
  "location": "germanywestcentral",
  "properties": {
    "provisioningState": "Succeeded",
    "resourceGuid": "a0b298d0-4158-9e84-0e902bec3f20",
    "serviceAlias": "/services/Azure/ManagedInstance",
    "serviceEndpointPolicyDefinitions": [],
    "contextualServiceEndpointPolicies": [
      {
        "id": "/subscriptions/<subscriptionId>/resourceGroups/rg-network/providers/Microsoft.Network/virtualNetworks/vnet-001/subnets/snet-sqlmi/contextualServiceEndpointPolicies/ManagedInstanceContextualPolicy"
      }
    ]
  },
  "kind": "Internal"
}'

**Comment by magodo** [comment]
@arun6106 Thank you for reaching out!

The skipped ones indicate we are unable to find the corresponding TF resource for those ARM resources. While if you are aware of the resource type of them, you can type the resource types manually.

The error and back UI interaction is as expected, in which case you'll find an Error indicator in the resources that hit export error. And you are also able to view the error via pressing <kbd>e</kbd> with focusing them.

The `--continue` is also behaving as expected, where it will just finish and print any export error for those resources, if any.

**Comment by arun6106** [comment]
Thanks for the quick response @magodo 

The issue is coming for storage account in 1 case. I tried defining proper TF resource type for the 4 **Skipped** resources, as shown below,

but it keeps coming back to the list resources page again, I did press **s** to save resource mapping after my changes and then pressed **w**

The storage account itself is exported properly but it also creates 4 resources inside it by default :- file, blob, table,queue. Which are being skipped.

Is this not the correct way ?

    ✅/subscriptions/<subscriptionId>/resourceGroups/rg-01/providers/Microsoft.Storage/storageAccounts/storageaccount01
    azurerm_storage_account.res-36

	❗️/subscriptions/<subscriptionId>/resourceGroups/rg-supportsrvcs-oracle-vdi-001/providers/Microsoft.Storage/storageAccounts/storageaccount01/blobServices/default
    azurerm_storage_blob.blob-1

    ❗️/subscriptions/<subscriptionId>/resourceGroups/rg-supportsrvcs-oracle-vdi-001/providers/Microsoft.Storage/storageAccounts/storageaccount01/fileServices/default
    azurerm_storage_share.fs-1

    ❗️/subscriptions/<subscriptionId>/resourceGroups/rg-supportsrvcs-oracle-vdi-001/providers/Microsoft.Storage/storageAccounts/storageaccount01/queueServices/default
    azurerm_storage_queue.queue-1

    ❗️/subscriptions/<subscriptionId>/resourceGroups/rg-supportsrvcs-oracle-vdi-001/providers/Microsoft.Storage/storageAccounts/storageaccount01/tableServices/default
    azurerm_storage_table.tbl-1

**Comment by arun6106** [comment]
can we somehow **delete** the skipped rows ? would make it easier, we'd then manage these resources manually later

**Comment by arun6106** [comment]
Yes, I had already tried that. Pressing `del` only puts them to `(Skip)` but they are already Skipped anyway.

![image](https://github.com/user-attachments/assets/249c9f95-42e9-40a6-9838-0781daa3cb83)

so looks like the only way to export these is  `--non-interactive --continue` as even in `Skip` mode, aztfexport does run into some issue and brings me back to list resources page.

Only with `--continue` it goes further.

is that understanding correct ? or `del` should be able to delete them from the listed resources

**Comment by magodo** [comment]
The skipped resources won't be exported at all, and won't block the export process. There must be some other resources failed to export, ends up blocking the process in your case.

**Comment by arun6106** [comment]
Noted and can confirm there are some other failures. 

Thanks @magodo For all the great help
