### ISSUE TITLE
How to avoid  "⣽" chars in the output of the aztfexport (--non-Interactive already used)

### ISSUE THREAD

**Issue by edsonestrella** [Azure/aztfexport#579]
Hi.

I am launching a script to batch dozens of aztfexport. 
Using --non--interactive allows me to do it, but I would like to save the output of each run without the "⣽" chars contained in   "⣽" Importing resources...", " "⣽"Initializing....", etc

This feature is great when it is running in an interactive mode, but it makes log files hard to get/process/keep.

Kind regards

**Comment by magodo** [comment]
You can use the `--plain-ui`.

**Comment by edsonestrella** [comment]
Yes it worked as I needed.
Thanks
