### ISSUE TITLE
Main.tf not created

### ISSUE THREAD

**Issue by clifpi** [Azure/aztfexport#580]
Hello, 
We followed the following MS article (https://learn.microsoft.com/en-us/azure/developer/terraform/azure-export-for-terraform/export-resources-hcl?tabs=azure-cli) and ran the command "aztfexport resource-group --non-interactive --hcl-only myResourceGroup" and pointed it to the correct resource group. It only created a provider.tf and terraform.tf. It did not create a main.tf. Additional exception files were also created. 
Is there any additional prerequisites or steps that were missed to get the main.tf created with all the resource tf code?

**Comment by magodo** [comment]
Could you checkout the content of `aztfexportResourceMapping.json` and `aztfexportSkippedResources.txt`. If both are empty, and if you are using azure cli for auth, it mostly means the resoruce group isn't belonging to the default subscription set by your azure cli, in which case you can manually specify the correct subscription by using `-s`.

**Comment by clifpi** [comment]
Hi,
Thabk you for your response. These files (the json and txt) are populated with content and are not empty. We are testing it now with the "az account set" command and empty directory. This has been tested in another environment with no main.tf created. Are there any other suggestions? Thank you.

**Comment by magodo** [comment]
Can you share the contents of json and txt files? Also, could you please provide the runtime log (via `--log-path <path>` and `--log-level debug`)?

**Comment by clifpi** [comment]
Here you go..I need to do the runtime. But we are experiencing this in
completely different environments which is unusual.

**Comment by clifpi** [comment]
It's not accepting --log-path
"aztfexport --log-path c:\temp rg -o tempdir3 --non-interactive --continue
--hcl-only rg-it-ecc-prod-eus-001"

**Comment by magodo** [comment]
Please put the options after `aztfexport rg`.

**Comment by clifpi** [comment]
Greetings,
See attached logs and json, I got this error
[image: image.png]

**Comment by magodo** [comment]
@clifpi image not uploaded.

**Comment by clifpi** [comment]
See attached

**Comment by magodo** [comment]
I'm not sure but replying via email seems won't upload anything back to the conversation here.

**Comment by clifpi** [comment]
How about now![Image](https://github.com/user-attachments/assets/5a20d30c-a4b1-439a-8757-5a6cf0f8fecd)

**Comment by clifpi** [comment]
Are you receiving the json logs I sent?

**Comment by magodo** [comment]
@clifpi no. From the error image above, it indicates either there is no resource in the resource group you've specified, or the default subscription set by your azure cli doesn't include this resource group, in which case you can manually specify the correct subscription by using `-s`.

**Comment by clifpi** [comment]
Hi,
There are resources in the resource group. Also we use az login and the az
account set --subscription command before we run aztfexport.

**Comment by magodo** [comment]
Are you able to export other resource groups? It can happen that the resource types are not supported by `azurerm` in this group. You can also test it with specifying `--provider-name azapi`.

**Comment by clifpi** [comment]
No, this has never worked. We have tried multiple resources groups
containing virtual machines. Were you able to read the logs?

**Comment by magodo** [comment]
@clifpi I didn't see the log any where.

**Comment by clifpi** [comment]
[aztfexport1.txt](https://github.com/user-attachments/files/18223583/aztfexport1.txt)
See attached log

**Comment by magodo** [comment]
@clifpi Picking one of the error message:

> 3399614467, Tag: 558133256\r\nPlease explicitly log in with:\r\naz login --scope https://management.azure.com/.default\n\n\n"
time=2024-12-20T09:53:15.367-05:00 level=ERROR msg="Terraform import failed" tf_addr=azurerm_network_interface.res-3 error="exit status 1\n\nError: retrieving Network Interface (Subscription: \"6f3ac26b-30bf-455c-9b7f-509b36bbba37\"\nResource Group Name: \"RG-IT-ECC-PROD-EUS-001\"\nNetwork Interface Name: \"nic-vmeccops002\"): authorizing request: running Azure CLI: exit status 1: ERROR: (pii). Status: Response_Status.Status_InteractionRequired, Error code: 3399614467, Tag: 558133256\r\nPlease explicitly log in with:\r\naz login --scope https://management.azure.com/.default\n\n\n"

It indicates your CLI login lacks permission needed.

**Comment by clifpi** [comment]
This article fixed the issue
https://learn.microsoft.com/en-us/answers/questions/2121715/terraform-is-unable-to-acquire-access-token-from-a
