### ISSUE TITLE
Imported properties fails validation on terraform plan because of case sensitivity.

### ISSUE THREAD

**Issue by klaspihl** [Azure/aztfexport#72]
azurerm_network_security_rule seams to import properties from Azure without any regard of **case sensitivity**.
```
"azurerm_network_security_rule": /SUBSCRIPTIONS/{}/RESOURCEGROUPS/{}/PROVIDERS/MICROSOFT.NETWORK/NETWORKSECURITYGROUPS/{}/SECURITYRULES/{}",
```
[Reference](https://github.com/Azure/aztfy/blob/ae5841880d2d62061b05c7449dab985bf5a535e2/mapping/mapping_gen.go#L411)
A NSG rule in Azure;
```json
"properties": {
                "securityRules": [
                    {
                        "name": "SMB",
                        "properties": {
                            "protocol": "TCP", // upper case
                            "sourcePortRange": "*",
                            "destinationPortRange": "445",
                            "sourceAddressPrefix": "*",
                            "destinationAddressPrefix": "*",
                            "access": "Allow",
                            "priority": 310,
                            "direction": "Inbound",
                            "sourcePortRanges": [],
                            "destinationPortRanges": [],
                            "sourceAddressPrefixes": [],
                            "destinationAddressPrefixes": []
                        }
                    }
                ]
            }
        },
```
At ‘terraform plan’ the validation fails at wrong *protocol*; “
> Error: expected protocol to be one of [* Tcp Udp Icmp Ah Esp], got TCP”

[Reference](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/network_security_rule#protocol)

**Comment by magodo** [comment]
@KlasPihl Thank you for submitting this!

This is actually not a bug in `aztfy`, but an inconsistency between the provider behavior (only allows `Tcp` since v3.0) and the service behavior (case insensitive), which is tracked in: https://github.com/hashicorp/terraform-provider-azurerm/issues/16092.

What `aztfy` does is simply call `terraform import` and convert the state to config. This means the `property` is set as `TCP` in the state after importing. This always indicates that in the remote platform, the `protocol` is set as `TCP`. So I assume after you manually change this to be `Tcp`, you'll hit a plan diff for it.

I'll keep this issue open for tracking purpose.

**Comment by HughPrince** [comment]
Hello, is there any update or workarounds to this challenge/change as in my current scenario I can't have the NSG rules being ripped off and re added when there is no actual change to them.

From testing today with different versions up to tf 1.2.8, azurerm 3.21.1 it shows:
 - The Azure end will set upper case but azurerm provider => 2.99.0 is forcing a validation of init-caps Tcp.
 - The result is that any NSG rules which have been implemented < azurerm 2.99.0 with upper case TCP will be removed/re-added as Tcp. If the resulting rule is opened and saved via the Azure console it will be changed to upper case. I'm not suggesting manual updates of the NSG rules in the Azure console, just backing up that Azure is would appear to be working with upper case for the protocol parameter.

I've tested modifying the tf code and state to be Tcp as a work around, but the remove/add is still triggered.

Any suggestions or workarounds welcomed and if not possible can this be investigated further to see if the validation can be updated to correctly validate against what Azure is expecting.

Of if I have the wrong end of the stick on why this validation has been added/changed happy to be corrected.

**Comment by magodo** [comment]
@HughPrince You can always use `ignore_changes` to suppress this diff.

**Comment by argeljoseph** [comment]
@HughPrince , were you able to do a workaround? I'm facing this as well after importing an NSG. I tried modifying the NSG state in the statefile to use _Tcp_ instead of _TCP_, and match with corresponding code but it's triggerring a change still. 

If I use ignore_changes, how will I specify to only ignore changes in the protocol? or the ignore covers the whole security rule?

**Comment by magodo** [comment]
@argeljoseph Use the path down to the property you want to ignore.

Meanwhile, I've submit a PR to fix the upstream issue: https://github.com/hashicorp/terraform-provider-azurerm/pull/18799.

**Comment by argeljoseph** [comment]
@magodo I'm a bit new and can't test but should it be like this?
```
lifecycle {
    ignore_changes = [
      security_rule["protocol"]
    ]
  }
```

**Comment by magodo** [comment]
@argeljoseph It should be something like:

```
lifecycle {
  ignore_changes = [
    security_rule.n.protocol,
  ]
}
```

(Note that the `n` above should be replaced with the exact index of the rule whose protocol you want to ignore)

**Comment by argeljoseph** [comment]
> @argeljoseph It should be something like:
> 
> ```
> lifecycle {
>   ignore_changes = [
>     security_rule.n.protocol,
>   ]
> }
> ```
> 
> (Note that the `n` above should be replaced with the exact index of the rule whose protocol you want to ignore)

If I ignore all, will this work? `security_rule.*.protocol` ?

**Comment by magodo** [comment]
@argeljoseph I just realized the `.n` doesn't work here as `security_rule` is a set rather than a list, which can't be indexed. If you want to ignore all security rules, you can use just use:

```
lifecycle {
  ignore_changes = [
    security_rule,
  ]
}
```

**Comment by argeljoseph** [comment]
> @argeljoseph I just realized the `.n` doesn't work here as `security_rule` is a set rather than a list, which can't be indexed. If you want to ignore all security rules, you can use just use:
> 
> ```
> lifecycle {
>   ignore_changes = [
>     security_rule,
>   ]
> }
> ```

Got it. I'll just do this for now until the fix is in. Thanks!

**Comment by argeljoseph** [comment]
@magodo , I tried this and still got the error.
![image](https://user-images.githubusercontent.com/3426950/196596669-e4f02ce0-7ae2-4900-b97d-fa0365af8a71.png)

**Comment by magodo** [comment]
You should set the `protocol` of the security rule to `Tcp`.

**Comment by argeljoseph** [comment]
> You should set the `protocol` of the security rule to `Tcp`.

oh yeah, that makes sense! Thanks for pointing that out!

**Comment by magodo** [comment]
Close this as the upstream PR https://github.com/hashicorp/terraform-provider-azurerm/pull/18799 is merged.

**Comment by aaron-baron** [comment]
> @magodo , I tried this and still got the error. ![image](https://user-images.githubusercontent.com/3426950/196596669-e4f02ce0-7ae2-4900-b97d-fa0365af8a71.png)

Error still exists

**Comment by magodo** [comment]
@aaron-baron This works fine for me, please ensure the provider under used is later than v3.28.0, which is the case for the latest release of `aztfexport`. Or if you are hitting similar casing problems for other resources, please submit a new issue.
